export const catalogue = [
  {
    id: "bk-berry-blackberry",
    name: "Ежевика",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-berry-blackberry.glb",
    size: 2.2,
    color: "#38223b",
    price: 1.5,
    thumbnail: "thumbnails/bk-berry-blackberry.jpg",
    source: "bk-berry-blackberry",
  },
  {
    id: "bk-berry-blueberry",
    name: "Голубика",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-berry-blueberry.glb",
    size: 1.2,
    color: "#414571",
    price: 1.5,
    thumbnail: "thumbnails/bk-berry-blueberry.jpg",
    source: "bk-berry-blueberry",
  },
  {
    id: "bk-berry-cherry",
    name: "Вишня",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-berry-cherry.glb",
    size: 3.5,
    color: "#982331",
    price: 1.5,
    thumbnail: "thumbnails/bk-berry-cherry.jpg",
    source: "bk-berry-cherry",
  },
  {
    id: "bk-berry-currant-red",
    name: "Спиральная свеча",
    project: "cakes",
    category: "topper",
    role: "topper",
    url: "models/bk-berry-currant-red.glb",
    size: 7,
    color: "#f1c58a",
    price: 8,
    thumbnail: "thumbnails/bk-berry-currant-red.jpg",
    source: "bk-berry-currant-red",
  },
  {
    id: "bk-berry-raspberry",
    name: "Малина",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-berry-raspberry.glb",
    size: 2,
    color: "#bf3d55",
    price: 1.5,
    thumbnail: "thumbnails/bk-berry-raspberry.jpg",
    source: "bk-berry-raspberry",
  },
  {
    id: "bk-berry-strawberry",
    name: "Клубника",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-berry-strawberry.glb",
    size: 3.2,
    color: "#bb3341",
    price: 1.5,
    thumbnail: "thumbnails/bk-berry-strawberry.jpg",
    source: "bk-berry-strawberry",
  },
  {
    id: "bk-decor-caramel-spiral",
    name: "Карамельная спираль",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-decor-caramel-spiral.glb",
    size: 4,
    color: "#b2702f",
    price: 2,
    thumbnail: "thumbnails/bk-decor-caramel-spiral.jpg",
    source: "bk-decor-caramel-spiral",
  },
  {
    id: "bk-decor-chocolate-shard",
    name: "Шоколадный лепесток",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-decor-chocolate-shard.glb",
    size: 5,
    color: "#4d2c22",
    price: 2,
    thumbnail: "thumbnails/bk-decor-chocolate-shard.jpg",
    source: "bk-decor-chocolate-shard",
  },
  {
    id: "bk-decor-cream-rosette",
    name: "Кремовая розетка",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-decor-cream-rosette.glb",
    size: 2.4,
    color: "#f2dfcf",
    price: 2,
    thumbnail: "thumbnails/bk-decor-cream-rosette.jpg",
    source: "bk-decor-cream-rosette",
  },
  {
    id: "bk-decor-crumble-cluster",
    name: "Хрустящий крамбл",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-decor-crumble-cluster.glb",
    size: 3,
    color: "#be8c50",
    price: 2,
    thumbnail: "thumbnails/bk-decor-crumble-cluster.jpg",
    source: "bk-decor-crumble-cluster",
  },
  {
    id: "bk-decor-glaze-drip-ring",
    name: "Шоколадные подтёки",
    project: "cakes",
    category: "decor",
    role: "glaze",
    url: "models/bk-decor-glaze-drip-ring.glb",
    size: 3,
    color: "#4d2c22",
    price: 12,
    thumbnail: "thumbnails/bk-decor-glaze-drip-ring.jpg",
    source: "bk-decor-glaze-drip-ring",
  },
  {
    id: "bk-decor-gold-flake",
    name: "Сусальное золото",
    project: "cakes",
    category: "decor",
    role: "foil",
    url: "models/bk-decor-gold-flake.glb",
    size: 3,
    color: "#c4a358",
    price: 2,
    thumbnail: "thumbnails/bk-decor-gold-flake.jpg",
    source: "bk-decor-gold-flake",
  },
  {
    id: "bk-decor-macaron",
    name: "Макарон",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-decor-macaron.glb",
    size: 3,
    color: "#f2dfcf",
    price: 5,
    thumbnail: "thumbnails/bk-decor-macaron.jpg",
    source: "bk-decor-macaron",
  },
  {
    id: "bk-decor-meringue-kiss",
    name: "Безе",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-decor-meringue-kiss.glb",
    size: 2.4,
    color: "#f2dfcf",
    price: 2,
    thumbnail: "thumbnails/bk-decor-meringue-kiss.jpg",
    source: "bk-decor-meringue-kiss",
  },
  {
    id: "bk-decor-shell-border",
    name: "Кремовый бордюр",
    project: "cakes",
    category: "decor",
    role: "border",
    url: "models/bk-decor-shell-border.glb",
    size: 3,
    color: "#f2dfcf",
    price: 12,
    thumbnail: "thumbnails/bk-decor-shell-border.jpg",
    source: "bk-decor-shell-border",
  },
  {
    id: "bk-decor-sprinkle-ball",
    name: "Сахарные жемчужины",
    project: "cakes",
    category: "decor",
    role: "sprinkle",
    url: "models/bk-decor-sprinkle-ball.glb",
    size: 3,
    color: "#f2dfcf",
    price: 0.3,
    thumbnail: "thumbnails/bk-decor-sprinkle-ball.jpg",
    source: "bk-decor-sprinkle-ball",
  },
  {
    id: "bk-decor-sprinkle-star",
    name: "Сахарные звёзды",
    project: "cakes",
    category: "decor",
    role: "sprinkle",
    url: "models/bk-decor-sprinkle-star.glb",
    size: 3,
    color: "#f2dfcf",
    price: 0.3,
    thumbnail: "thumbnails/bk-decor-sprinkle-star.jpg",
    source: "bk-decor-sprinkle-star",
  },
  {
    id: "bk-decor-truffle-ball",
    name: "Шоколадный трюфель",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-decor-truffle-ball.glb",
    size: 3,
    color: "#4d2c22",
    price: 2,
    thumbnail: "thumbnails/bk-decor-truffle-ball.jpg",
    source: "bk-decor-truffle-ball",
  },
  {
    id: "bk-decor-wafer-roll",
    name: "Вафельная трубочка",
    project: "cakes",
    category: "decor",
    role: "decor",
    url: "models/bk-decor-wafer-roll.glb",
    size: 5,
    color: "#f2dfcf",
    price: 2,
    thumbnail: "thumbnails/bk-decor-wafer-roll.jpg",
    source: "bk-decor-wafer-roll",
  },
  {
    id: "bk-pastry-brownie-bite",
    name: "Брауни",
    project: "cakes",
    category: "base",
    role: "base",
    url: "models/bk-pastry-brownie-bite.glb",
    size: 3,
    color: "#f2dfcf",
    price: 7,
    thumbnail: "thumbnails/bk-pastry-brownie-bite.jpg",
    source: "bk-pastry-brownie-bite",
  },
  {
    id: "bk-pastry-cookie-heart",
    name: "Печенье-сердце",
    project: "cakes",
    category: "base",
    role: "base",
    url: "models/bk-pastry-cookie-heart.glb",
    size: 3,
    color: "#f2dfcf",
    price: 5,
    thumbnail: "thumbnails/bk-pastry-cookie-heart.jpg",
    source: "bk-pastry-cookie-heart",
  },
  {
    id: "bk-pastry-cookie-round",
    name: "Сахарное печенье",
    project: "cakes",
    category: "base",
    role: "base",
    url: "models/bk-pastry-cookie-round.glb",
    size: 3,
    color: "#f2dfcf",
    price: 4,
    thumbnail: "thumbnails/bk-pastry-cookie-round.jpg",
    source: "bk-pastry-cookie-round",
  },
  {
    id: "bk-pastry-cupcake",
    name: "Капкейк",
    project: "cakes",
    category: "base",
    role: "base",
    url: "models/bk-pastry-cupcake.glb",
    size: 3,
    color: "#f2dfcf",
    price: 8,
    thumbnail: "thumbnails/bk-pastry-cupcake.jpg",
    source: "bk-pastry-cupcake",
  },
  {
    id: "bk-pastry-donut",
    name: "Пончик",
    project: "cakes",
    category: "base",
    role: "base",
    url: "models/bk-pastry-donut.glb",
    size: 3,
    color: "#f2dfcf",
    price: 6,
    thumbnail: "thumbnails/bk-pastry-donut.jpg",
    source: "bk-pastry-donut",
  },
  {
    id: "bk-pastry-eclair",
    name: "Эклер",
    project: "cakes",
    category: "base",
    role: "base",
    url: "models/bk-pastry-eclair.glb",
    size: 3,
    color: "#f2dfcf",
    price: 9,
    thumbnail: "thumbnails/bk-pastry-eclair.jpg",
    source: "bk-pastry-eclair",
  },
  {
    id: "bk-pastry-profiterole",
    name: "Профитроль",
    project: "cakes",
    category: "base",
    role: "base",
    url: "models/bk-pastry-profiterole.glb",
    size: 3,
    color: "#f2dfcf",
    price: 5,
    thumbnail: "thumbnails/bk-pastry-profiterole.jpg",
    source: "bk-pastry-profiterole",
  },
  {
    id: "bk-struct-tier-hex",
    name: "Шестиугольный торт",
    project: "cakes",
    category: "base",
    role: "base",
    url: "models/bk-struct-tier-hex.glb",
    size: 3,
    color: "#f2dfcf",
    price: 85,
    thumbnail: "thumbnails/bk-struct-tier-hex.jpg",
    source: "bk-struct-tier-hex",
  },
  {
    id: "bk-struct-tier-round",
    name: "Круглый торт",
    project: "cakes",
    category: "base",
    role: "base",
    url: "models/bk-struct-tier-round.glb",
    size: 3,
    color: "#f2dfcf",
    price: 85,
    thumbnail: "thumbnails/bk-struct-tier-round.jpg",
    source: "bk-struct-tier-round",
  },
  {
    id: "bk-topper-banner-blank",
    name: "Праздничный флажок",
    project: "cakes",
    category: "topper",
    role: "topper",
    url: "models/bk-topper-banner-blank.glb",
    size: 3,
    color: "#f2dfcf",
    price: 8,
    thumbnail: "thumbnails/bk-topper-banner-blank.jpg",
    source: "bk-topper-banner-blank",
  },
  {
    id: "bk-topper-crown",
    name: "Корона",
    project: "cakes",
    category: "topper",
    role: "topper",
    url: "models/bk-topper-crown.glb",
    size: 3,
    color: "#f2dfcf",
    price: 8,
    thumbnail: "thumbnails/bk-topper-crown.jpg",
    source: "bk-topper-crown",
  },
  {
    id: "bk-topper-heart",
    name: "Сердце",
    project: "cakes",
    category: "topper",
    role: "topper",
    url: "models/bk-topper-heart.glb",
    size: 3,
    color: "#f2dfcf",
    price: 8,
    thumbnail: "thumbnails/bk-topper-heart.jpg",
    source: "bk-topper-heart",
  },
  {
    id: "bk-topper-horn",
    name: "Единорог",
    project: "cakes",
    category: "topper",
    role: "topper",
    url: "models/bk-topper-horn.glb",
    size: 3,
    color: "#f2dfcf",
    price: 8,
    thumbnail: "thumbnails/bk-topper-horn.jpg",
    source: "bk-topper-horn",
  },
  {
    id: "bk-topper-star",
    name: "Звезда",
    project: "cakes",
    category: "topper",
    role: "topper",
    url: "models/bk-topper-star.glb",
    size: 3,
    color: "#f2dfcf",
    price: 8,
    thumbnail: "thumbnails/bk-topper-star.jpg",
    source: "bk-topper-star",
  },
  {
    id: "fl-fill-gypsophila",
    name: "Гипсофила",
    project: "flowers",
    category: "green",
    role: "green",
    url: "models/fl-fill-gypsophila.glb",
    size: 7,
    color: "#e7e5cf",
    price: 7,
    thumbnail: "thumbnails/fl-fill-gypsophila.jpg",
    source: "fl-fill-gypsophila",
  },
  {
    id: "fl-fill-solidago",
    name: "Солидаго",
    project: "flowers",
    category: "green",
    role: "green",
    url: "models/fl-fill-solidago.glb",
    size: 7,
    color: "#c3a545",
    price: 7,
    thumbnail: "thumbnails/fl-fill-solidago.jpg",
    source: "fl-fill-solidago",
  },
  {
    id: "fl-flower-anemone",
    name: "Анемона",
    project: "flowers",
    category: "flowers",
    role: "flowers",
    url: "models/fl-flower-anemone.glb",
    size: 7,
    color: "#cf829d",
    price: 10,
    thumbnail: "thumbnails/fl-flower-anemone.jpg",
    source: "fl-flower-anemone",
  },
  {
    id: "fl-flower-chamomile",
    name: "Ромашка",
    project: "flowers",
    category: "flowers",
    role: "flowers",
    url: "models/fl-flower-chamomile.glb",
    size: 5.5,
    color: "#cf829d",
    price: 10,
    thumbnail: "thumbnails/fl-flower-chamomile.jpg",
    source: "fl-flower-chamomile",
  },
  {
    id: "fl-flower-chrysanthemum-spray",
    name: "Хризантема",
    project: "flowers",
    category: "flowers",
    role: "flowers",
    url: "models/fl-flower-chrysanthemum-spray.glb",
    size: 7,
    color: "#cf829d",
    price: 10,
    thumbnail: "thumbnails/fl-flower-chrysanthemum-spray.jpg",
    source: "fl-flower-chrysanthemum-spray",
  },
  {
    id: "fl-flower-eustoma",
    name: "Эустома",
    project: "flowers",
    category: "flowers",
    role: "flowers",
    url: "models/fl-flower-eustoma.glb",
    size: 7,
    color: "#cf829d",
    price: 10,
    thumbnail: "thumbnails/fl-flower-eustoma.jpg",
    source: "fl-flower-eustoma",
  },
  {
    id: "fl-flower-gerbera",
    name: "Гербера",
    project: "flowers",
    category: "flowers",
    role: "flowers",
    url: "models/fl-flower-gerbera.glb",
    size: 7,
    color: "#cf829d",
    price: 10,
    thumbnail: "thumbnails/fl-flower-gerbera.jpg",
    source: "fl-flower-gerbera",
  },
  {
    id: "fl-flower-lily-oriental",
    name: "Восточная лилия",
    project: "flowers",
    category: "flowers",
    role: "flowers",
    url: "models/fl-flower-lily-oriental.glb",
    size: 9,
    color: "#cf829d",
    price: 10,
    thumbnail: "thumbnails/fl-flower-lily-oriental.jpg",
    source: "fl-flower-lily-oriental",
  },
  {
    id: "fl-flower-peony-open",
    name: "Пион",
    project: "flowers",
    category: "flowers",
    role: "flowers",
    url: "models/fl-flower-peony-open.glb",
    size: 8,
    color: "#cf829d",
    price: 10,
    thumbnail: "thumbnails/fl-flower-peony-open.jpg",
    source: "fl-flower-peony-open",
  },
  {
    id: "fl-flower-ranunculus",
    name: "Ранункулюс",
    project: "flowers",
    category: "flowers",
    role: "flowers",
    url: "models/fl-flower-ranunculus.glb",
    size: 7,
    color: "#cf829d",
    price: 10,
    thumbnail: "thumbnails/fl-flower-ranunculus.jpg",
    source: "fl-flower-ranunculus",
  },
  {
    id: "fl-flower-rose-garden",
    name: "Садовая роза",
    project: "flowers",
    category: "flowers",
    role: "flowers",
    url: "models/fl-flower-rose-garden.glb",
    size: 7,
    color: "#cf829d",
    price: 10,
    thumbnail: "thumbnails/fl-flower-rose-garden.jpg",
    source: "fl-flower-rose-garden",
  },
  {
    id: "fl-flower-tulip",
    name: "Тюльпан",
    project: "flowers",
    category: "flowers",
    role: "flowers",
    url: "models/fl-flower-tulip.glb",
    size: 4.5,
    color: "#cf829d",
    price: 10,
    thumbnail: "thumbnails/fl-flower-tulip.jpg",
    source: "fl-flower-tulip",
  },
  {
    id: "fl-green-eucalyptus-baby-blue",
    name: "Эвкалипт Baby Blue",
    project: "flowers",
    category: "green",
    role: "green",
    url: "models/fl-green-eucalyptus-baby-blue.glb",
    size: 7,
    color: "#57705a",
    price: 7,
    thumbnail: "thumbnails/fl-green-eucalyptus-baby-blue.jpg",
    source: "fl-green-eucalyptus-baby-blue",
  },
  {
    id: "fl-green-eucalyptus-silver",
    name: "Серебристый эвкалипт",
    project: "flowers",
    category: "green",
    role: "green",
    url: "models/fl-green-eucalyptus-silver.glb",
    size: 7,
    color: "#57705a",
    price: 7,
    thumbnail: "thumbnails/fl-green-eucalyptus-silver.jpg",
    source: "fl-green-eucalyptus-silver",
  },
  {
    id: "fl-green-fern",
    name: "Папоротник",
    project: "flowers",
    category: "green",
    role: "green",
    url: "models/fl-green-fern.glb",
    size: 7,
    color: "#57705a",
    price: 7,
    thumbnail: "thumbnails/fl-green-fern.jpg",
    source: "fl-green-fern",
  },
  {
    id: "fl-green-lagurus",
    name: "Лагурус",
    project: "flowers",
    category: "green",
    role: "green",
    url: "models/fl-green-lagurus.glb",
    size: 7,
    color: "#57705a",
    price: 7,
    thumbnail: "thumbnails/fl-green-lagurus.jpg",
    source: "fl-green-lagurus",
  },
  {
    id: "fl-green-olive-branch",
    name: "Оливковая ветвь",
    project: "flowers",
    category: "green",
    role: "green",
    url: "models/fl-green-olive-branch.glb",
    size: 7,
    color: "#57705a",
    price: 7,
    thumbnail: "thumbnails/fl-green-olive-branch.jpg",
    source: "fl-green-olive-branch",
  },
  {
    id: "fl-green-ruscus",
    name: "Рускус",
    project: "flowers",
    category: "green",
    role: "green",
    url: "models/fl-green-ruscus.glb",
    size: 7,
    color: "#57705a",
    price: 7,
    thumbnail: "thumbnails/fl-green-ruscus.jpg",
    source: "fl-green-ruscus",
  },
  {
    id: "fl-ribbon-jute-twine",
    name: "Джутовая нить",
    project: "flowers",
    category: "ribbon",
    role: "ribbon",
    url: "models/fl-ribbon-jute-twine.glb",
    size: 7,
    color: "#cf829d",
    price: 7,
    thumbnail: "thumbnails/fl-ribbon-jute-twine.jpg",
    source: "fl-ribbon-jute-twine",
  },
  {
    id: "fl-ribbon-rep-bow",
    name: "Репсовый бант",
    project: "flowers",
    category: "ribbon",
    role: "ribbon",
    url: "models/fl-ribbon-rep-bow.glb",
    size: 7,
    color: "#cf829d",
    price: 7,
    thumbnail: "thumbnails/fl-ribbon-rep-bow.jpg",
    source: "fl-ribbon-rep-bow",
  },
  {
    id: "fl-ribbon-satin-bow",
    name: "Атласный бант",
    project: "flowers",
    category: "ribbon",
    role: "ribbon",
    url: "models/fl-ribbon-satin-bow.glb",
    size: 7,
    color: "#cf829d",
    price: 7,
    thumbnail: "thumbnails/fl-ribbon-satin-bow.jpg",
    source: "fl-ribbon-satin-bow",
  },
  {
    id: "fl-vase-bottle-ceramic",
    name: "Керамическая ваза",
    project: "flowers",
    category: "pack",
    role: "pack",
    url: "models/fl-vase-bottle-ceramic.glb",
    size: 7,
    color: "#cab594",
    price: 20,
    thumbnail: "thumbnails/fl-vase-bottle-ceramic.jpg",
    source: "fl-vase-bottle-ceramic",
  },
  {
    id: "fl-vase-glass-cylinder",
    name: "Стеклянная ваза",
    project: "flowers",
    category: "pack",
    role: "pack",
    url: "models/fl-vase-glass-cylinder.glb",
    size: 7,
    color: "#cab594",
    price: 20,
    thumbnail: "thumbnails/fl-vase-glass-cylinder.jpg",
    source: "fl-vase-glass-cylinder",
  },
  {
    id: "fl-vase-kraft-bucket",
    name: "Крафтовое ведёрко",
    project: "flowers",
    category: "pack",
    role: "pack",
    url: "models/fl-vase-kraft-bucket.glb",
    size: 7,
    color: "#cab594",
    price: 20,
    thumbnail: "thumbnails/fl-vase-kraft-bucket.jpg",
    source: "fl-vase-kraft-bucket",
  },
  {
    id: "fl-wrap-basket-rattan",
    name: "Плетёная корзина",
    project: "flowers",
    category: "pack",
    role: "pack",
    url: "models/fl-wrap-basket-rattan.glb",
    size: 7,
    color: "#cab594",
    price: 20,
    thumbnail: "thumbnails/fl-wrap-basket-rattan.jpg",
    source: "fl-wrap-basket-rattan",
  },
  {
    id: "fl-wrap-hatbox-round",
    name: "Шляпная коробка",
    project: "flowers",
    category: "pack",
    role: "pack",
    url: "models/fl-wrap-hatbox-round.glb",
    size: 7,
    color: "#cab594",
    price: 20,
    thumbnail: "thumbnails/fl-wrap-hatbox-round.jpg",
    source: "fl-wrap-hatbox-round",
  },
  {
    id: "fl-wrap-kraft-cone",
    name: "Крафтовый конверт",
    project: "flowers",
    category: "pack",
    role: "pack",
    url: "models/fl-wrap-kraft-cone.glb",
    size: 7,
    color: "#cab594",
    price: 20,
    thumbnail: "thumbnails/fl-wrap-kraft-cone.jpg",
    source: "fl-wrap-kraft-cone",
  },
  {
    id: "fl-wrap-matte-sleeve",
    name: "Матовая упаковка",
    project: "flowers",
    category: "pack",
    role: "pack",
    url: "models/fl-wrap-matte-sleeve.glb",
    size: 7,
    color: "#cab594",
    price: 20,
    thumbnail: "thumbnails/fl-wrap-matte-sleeve.jpg",
    source: "fl-wrap-matte-sleeve",
  },
  {
    id: "jw-base-band-plain",
    name: "Гладкое кольцо",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-base-band-plain.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-base-band-plain.jpg",
    source: "jw-base-band-plain",
  },
  {
    id: "jw-base-chain-link-cable",
    name: "Звеньевая цепь",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-base-chain-link-cable.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-base-chain-link-cable.jpg",
    source: "jw-base-chain-link-cable",
  },
  {
    id: "jw-base-cocktail",
    name: "Коктейльное кольцо",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-base-cocktail.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-base-cocktail.jpg",
    source: "jw-base-cocktail",
  },
  {
    id: "jw-base-cuff-bracelet",
    name: "Браслет-манжета",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-base-cuff-bracelet.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-base-cuff-bracelet.jpg",
    source: "jw-base-cuff-bracelet",
  },
  {
    id: "jw-base-drop-earring",
    name: "Серьга-капля",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-base-drop-earring.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-base-drop-earring.jpg",
    source: "jw-base-drop-earring",
  },
  {
    id: "jw-base-ear-cuff",
    name: "Кафф",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-base-ear-cuff.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-base-ear-cuff.jpg",
    source: "jw-base-ear-cuff",
  },
  {
    id: "jw-base-pendant",
    name: "Ажурная подвеска",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-base-pendant.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-base-pendant.jpg",
    source: "jw-base-pendant",
  },
  {
    id: "jw-base-signet",
    name: "Печатка",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-base-signet.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-base-signet.jpg",
    source: "jw-base-signet",
  },
  {
    id: "jw-base-solitaire",
    name: "Солитер",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-base-solitaire.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-base-solitaire.jpg",
    source: "jw-base-solitaire",
  },
  {
    id: "jw-base-stacking-thin",
    name: "Тонкое кольцо",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-base-stacking-thin.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-base-stacking-thin.jpg",
    source: "jw-base-stacking-thin",
  },
  {
    id: "jw-base-stud-earring",
    name: "Серьга-гвоздик",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-base-stud-earring.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-base-stud-earring.jpg",
    source: "jw-base-stud-earring",
  },
  {
    id: "jw-part-bail-hinged",
    name: "Держатель подвески",
    project: "jewelry",
    category: "finding",
    role: "finding",
    url: "models/jw-part-bail-hinged.glb",
    size: 1,
    color: "#c9a866",
    price: 25,
    thumbnail: "thumbnails/jw-part-bail-hinged.jpg",
    source: "jw-part-bail-hinged",
  },
  {
    id: "jw-part-charm-tag",
    name: "Шарм-медальон",
    project: "jewelry",
    category: "finding",
    role: "finding",
    url: "models/jw-part-charm-tag.glb",
    size: 1,
    color: "#c9a866",
    price: 25,
    thumbnail: "thumbnails/jw-part-charm-tag.jpg",
    source: "jw-part-charm-tag",
  },
  {
    id: "jw-part-clasp-lobster",
    name: "Замок-карабин",
    project: "jewelry",
    category: "finding",
    role: "finding",
    url: "models/jw-part-clasp-lobster.glb",
    size: 1,
    color: "#c9a866",
    price: 25,
    thumbnail: "thumbnails/jw-part-clasp-lobster.jpg",
    source: "jw-part-clasp-lobster",
  },
  {
    id: "jw-part-ear-wire-french",
    name: "Французская швенза",
    project: "jewelry",
    category: "finding",
    role: "finding",
    url: "models/jw-part-ear-wire-french.glb",
    size: 1,
    color: "#c9a866",
    price: 25,
    thumbnail: "thumbnails/jw-part-ear-wire-french.jpg",
    source: "jw-part-ear-wire-french",
  },
  {
    id: "jw-part-jump-ring",
    name: "Соединительное кольцо",
    project: "jewelry",
    category: "finding",
    role: "finding",
    url: "models/jw-part-jump-ring.glb",
    size: 1,
    color: "#c9a866",
    price: 25,
    thumbnail: "thumbnails/jw-part-jump-ring.jpg",
    source: "jw-part-jump-ring",
  },
  {
    id: "jw-set-baguette",
    name: "Оправа багет",
    project: "jewelry",
    category: "setting",
    role: "setting",
    url: "models/jw-set-baguette.glb",
    size: 1,
    color: "#c9a866",
    price: 25,
    thumbnail: "thumbnails/jw-set-baguette.jpg",
    source: "jw-set-baguette",
  },
  {
    id: "jw-set-bezel",
    name: "Кольцо с глухой оправой",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-set-bezel.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-set-bezel.jpg",
    source: "jw-set-bezel",
  },
  {
    id: "jw-set-halo",
    name: "Кольцо с ореолом",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-set-halo.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-set-halo.jpg",
    source: "jw-set-halo",
  },
  {
    id: "jw-set-heart",
    name: "Оправа-сердце",
    project: "jewelry",
    category: "setting",
    role: "setting",
    url: "models/jw-set-heart.glb",
    size: 1,
    color: "#c9a866",
    price: 25,
    thumbnail: "thumbnails/jw-set-heart.jpg",
    source: "jw-set-heart",
  },
  {
    id: "jw-set-marquise",
    name: "Оправа-маркиз",
    project: "jewelry",
    category: "setting",
    role: "setting",
    url: "models/jw-set-marquise.glb",
    size: 1,
    color: "#c9a866",
    price: 25,
    thumbnail: "thumbnails/jw-set-marquise.jpg",
    source: "jw-set-marquise",
  },
  {
    id: "jw-set-pave-band",
    name: "Браслет паве",
    project: "jewelry",
    category: "base",
    role: "base",
    url: "models/jw-set-pave-band.glb",
    size: 1,
    color: "#c9a866",
    price: 160,
    thumbnail: "thumbnails/jw-set-pave-band.jpg",
    source: "jw-set-pave-band",
  },
  {
    id: "jw-set-pear",
    name: "Оправа-капля",
    project: "jewelry",
    category: "setting",
    role: "setting",
    url: "models/jw-set-pear.glb",
    size: 1,
    color: "#c9a866",
    price: 25,
    thumbnail: "thumbnails/jw-set-pear.jpg",
    source: "jw-set-pear",
  },
  {
    id: "jw-set-prong4",
    name: "Четыре крапана",
    project: "jewelry",
    category: "setting",
    role: "setting",
    url: "models/jw-set-prong4.glb",
    size: 1,
    color: "#c9a866",
    price: 25,
    thumbnail: "thumbnails/jw-set-prong4.jpg",
    source: "jw-set-prong4",
  },
  {
    id: "jw-set-prong6",
    name: "Шесть крапанов",
    project: "jewelry",
    category: "setting",
    role: "setting",
    url: "models/jw-set-prong6.glb",
    size: 1,
    color: "#c9a866",
    price: 25,
    thumbnail: "thumbnails/jw-set-prong6.jpg",
    source: "jw-set-prong6",
  },
  {
    id: "jw-stone-cabochon-oval",
    name: "Овальный кабошон",
    project: "jewelry",
    category: "stone",
    role: "stone",
    url: "models/jw-stone-cabochon-oval.glb",
    size: 1,
    color: "#397b68",
    price: 75,
    thumbnail: "thumbnails/jw-stone-cabochon-oval.jpg",
    source: "jw-stone-cabochon-oval",
  },
  {
    id: "jw-stone-round-brilliant",
    name: "Круглый бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    url: "models/jw-stone-round-brilliant.glb",
    size: 1,
    color: "#e6edf0",
    price: 75,
    thumbnail: "thumbnails/jw-stone-round-brilliant.jpg",
    source: "jw-stone-round-brilliant",
  },
  {
    id: "jw-stone-diamond-01",
    url: "models/stones/jw-stone-diamond-01.glb",
    pack: "diamond",
    index: 1,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 476,
    name: "Багет",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-01.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-diamond-02",
    url: "models/stones/jw-stone-diamond-02.glb",
    pack: "diamond",
    index: 2,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane.002_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 538,
    name: "Кушон",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-02.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-diamond-03",
    url: "models/stones/jw-stone-diamond-03.glb",
    pack: "diamond",
    index: 3,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane.003_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 1384,
    name: "Сердце",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-03.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-diamond-04",
    url: "models/stones/jw-stone-diamond-04.glb",
    pack: "diamond",
    index: 4,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane.004_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 1848,
    name: "Ашер",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-04.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-diamond-05",
    url: "models/stones/jw-stone-diamond-05.glb",
    pack: "diamond",
    index: 5,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane.005_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 3276,
    name: "Ступенчатая огранка",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-05.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-diamond-06",
    url: "models/stones/jw-stone-diamond-06.glb",
    pack: "diamond",
    index: 6,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane.006_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 956,
    name: "Изумрудная",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-06.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-diamond-07",
    url: "models/stones/jw-stone-diamond-07.glb",
    pack: "diamond",
    index: 7,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane.007_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 70,
    name: "Принцесса",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-07.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-diamond-08",
    url: "models/stones/jw-stone-diamond-08.glb",
    pack: "diamond",
    index: 8,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane.008_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 222,
    name: "Круглая",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-08.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-diamond-09",
    url: "models/stones/jw-stone-diamond-09.glb",
    pack: "diamond",
    index: 9,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane.009_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 1184,
    name: "Овал",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-09.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-diamond-10",
    url: "models/stones/jw-stone-diamond-10.glb",
    pack: "diamond",
    index: 10,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane.010_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 180,
    name: "Маркиз",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-10.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-diamond-11",
    url: "models/stones/jw-stone-diamond-11.glb",
    pack: "diamond",
    index: 11,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane.011_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 188,
    name: "Груша",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-11.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-diamond-12",
    url: "models/stones/jw-stone-diamond-12.glb",
    pack: "diamond",
    index: 12,
    sourceFile: "diamond_gem_shape_set_-_1_collectibles.glb",
    sourceNode: "Plane.001_Diamond_Master_0",
    sourceMaterial: "Diamond_Master",
    triangles: 388,
    name: "Триллион",
    variant: "Бриллиант",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 95,
    thumbnail: "thumbnails/jw-stone-diamond-12.jpg",
    face: "z",
    source: "jw-stone/diamond_gem_shape_set_-_1_collectibles.glb",
  },
  {
    id: "jw-stone-gem-01",
    url: "models/stones/jw-stone-gem-01.glb",
    pack: "gem",
    index: 1,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_4",
    sourceMaterial: "White_-_abochon",
    triangles: 640,
    name: "Овальный кабошон",
    variant: "Бесцветный",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-01.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-02",
    url: "models/stones/jw-stone-gem-02.glb",
    pack: "gem",
    index: 2,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_6",
    sourceMaterial: "Light_Blue_-_abochon",
    triangles: 2688,
    name: "Овальный кабошон",
    variant: "Аквамарин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8fcee3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-02.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-03",
    url: "models/stones/jw-stone-gem-03.glb",
    pack: "gem",
    index: 3,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_8",
    sourceMaterial: "Green_-_abochon",
    triangles: 2688,
    name: "Овальный кабошон",
    variant: "Изумруд",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#2b886b",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-03.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-04",
    url: "models/stones/jw-stone-gem-04.glb",
    pack: "gem",
    index: 4,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_10",
    sourceMaterial: "Red_-_abochon",
    triangles: 2688,
    name: "Овальный кабошон",
    variant: "Рубин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#a92445",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-04.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-05",
    url: "models/stones/jw-stone-gem-05.glb",
    pack: "gem",
    index: 5,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_12",
    sourceMaterial: "Purple_-_abochon",
    triangles: 2688,
    name: "Овальный кабошон",
    variant: "Аметист",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8e66b3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-05.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-06",
    url: "models/stones/jw-stone-gem-06.glb",
    pack: "gem",
    index: 6,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_14",
    sourceMaterial: "Orange_-_abochon",
    triangles: 2688,
    name: "Овальный кабошон",
    variant: "Цитрин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d18b3d",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-06.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-07",
    url: "models/stones/jw-stone-gem-07.glb",
    pack: "gem",
    index: 7,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_16",
    sourceMaterial: "Blue_-_abochon",
    triangles: 2688,
    name: "Овальный кабошон",
    variant: "Сапфир",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#345caa",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-07.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-08",
    url: "models/stones/jw-stone-gem-08.glb",
    pack: "gem",
    index: 8,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_18",
    sourceMaterial: "Yellow_-_abochon",
    triangles: 2688,
    name: "Овальный кабошон",
    variant: "Жёлтый топаз",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d9b351",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-08.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-09",
    url: "models/stones/jw-stone-gem-09.glb",
    pack: "gem",
    index: 9,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_20",
    sourceMaterial: "White_-_abochon",
    triangles: 510,
    name: "Круглый кабошон",
    variant: "Бесцветный",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-09.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-10",
    url: "models/stones/jw-stone-gem-10.glb",
    pack: "gem",
    index: 10,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_22",
    sourceMaterial: "Light_Blue_-_abochon",
    triangles: 510,
    name: "Круглый кабошон",
    variant: "Аквамарин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8fcee3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-10.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-11",
    url: "models/stones/jw-stone-gem-11.glb",
    pack: "gem",
    index: 11,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_24",
    sourceMaterial: "Green_-_abochon",
    triangles: 510,
    name: "Круглый кабошон",
    variant: "Изумруд",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#2b886b",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-11.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-12",
    url: "models/stones/jw-stone-gem-12.glb",
    pack: "gem",
    index: 12,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_26",
    sourceMaterial: "Red_-_abochon",
    triangles: 510,
    name: "Круглый кабошон",
    variant: "Рубин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#a92445",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-12.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-13",
    url: "models/stones/jw-stone-gem-13.glb",
    pack: "gem",
    index: 13,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_28",
    sourceMaterial: "Purple_-_abochon",
    triangles: 510,
    name: "Круглый кабошон",
    variant: "Аметист",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8e66b3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-13.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-14",
    url: "models/stones/jw-stone-gem-14.glb",
    pack: "gem",
    index: 14,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_30",
    sourceMaterial: "Orange_-_abochon",
    triangles: 510,
    name: "Круглый кабошон",
    variant: "Цитрин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d18b3d",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-14.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-15",
    url: "models/stones/jw-stone-gem-15.glb",
    pack: "gem",
    index: 15,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_32",
    sourceMaterial: "Blue_-_abochon",
    triangles: 510,
    name: "Круглый кабошон",
    variant: "Сапфир",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#345caa",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-15.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-16",
    url: "models/stones/jw-stone-gem-16.glb",
    pack: "gem",
    index: 16,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_34",
    sourceMaterial: "Yellow_-_abochon",
    triangles: 510,
    name: "Круглый кабошон",
    variant: "Жёлтый топаз",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d9b351",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-16.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-17",
    url: "models/stones/jw-stone-gem-17.glb",
    pack: "gem",
    index: 17,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_36",
    sourceMaterial: "Light_Blue_-_Gem",
    triangles: 302,
    name: "Бриллиант",
    variant: "Аквамарин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8fcee3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-17.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-18",
    url: "models/stones/jw-stone-gem-18.glb",
    pack: "gem",
    index: 18,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_38",
    sourceMaterial: "Green_-_Gem",
    triangles: 302,
    name: "Бриллиант",
    variant: "Изумруд",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#2b886b",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-18.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-19",
    url: "models/stones/jw-stone-gem-19.glb",
    pack: "gem",
    index: 19,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_40",
    sourceMaterial: "Red_-_Gem",
    triangles: 302,
    name: "Бриллиант",
    variant: "Рубин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#a92445",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-19.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-20",
    url: "models/stones/jw-stone-gem-20.glb",
    pack: "gem",
    index: 20,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_42",
    sourceMaterial: "Purple_-_Gem",
    triangles: 302,
    name: "Бриллиант",
    variant: "Аметист",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8e66b3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-20.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-21",
    url: "models/stones/jw-stone-gem-21.glb",
    pack: "gem",
    index: 21,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_44",
    sourceMaterial: "Orange_-_Gem",
    triangles: 302,
    name: "Бриллиант",
    variant: "Цитрин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d18b3d",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-21.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-22",
    url: "models/stones/jw-stone-gem-22.glb",
    pack: "gem",
    index: 22,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_46",
    sourceMaterial: "Blue_-_Gem",
    triangles: 302,
    name: "Бриллиант",
    variant: "Сапфир",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#345caa",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-22.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-23",
    url: "models/stones/jw-stone-gem-23.glb",
    pack: "gem",
    index: 23,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_48",
    sourceMaterial: "Yellow_-_Gem",
    triangles: 302,
    name: "Бриллиант",
    variant: "Жёлтый топаз",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d9b351",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-23.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-24",
    url: "models/stones/jw-stone-gem-24.glb",
    pack: "gem",
    index: 24,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_50",
    sourceMaterial: "White_-_Gem",
    triangles: 302,
    name: "Бриллиант",
    variant: "Бесцветный",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-24.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-25",
    url: "models/stones/jw-stone-gem-25.glb",
    pack: "gem",
    index: 25,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_52",
    sourceMaterial: "Light_Blue_-_Gem",
    triangles: 140,
    name: "Изумрудная",
    variant: "Аквамарин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8fcee3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-25.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-26",
    url: "models/stones/jw-stone-gem-26.glb",
    pack: "gem",
    index: 26,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_54",
    sourceMaterial: "Green_-_Gem",
    triangles: 140,
    name: "Изумрудная",
    variant: "Изумруд",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#2b886b",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-26.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-27",
    url: "models/stones/jw-stone-gem-27.glb",
    pack: "gem",
    index: 27,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_56",
    sourceMaterial: "Red_-_Gem",
    triangles: 140,
    name: "Изумрудная",
    variant: "Рубин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#a92445",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-27.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-28",
    url: "models/stones/jw-stone-gem-28.glb",
    pack: "gem",
    index: 28,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_58",
    sourceMaterial: "Purple_-_Gem",
    triangles: 140,
    name: "Изумрудная",
    variant: "Аметист",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8e66b3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-28.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-29",
    url: "models/stones/jw-stone-gem-29.glb",
    pack: "gem",
    index: 29,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_60",
    sourceMaterial: "Orange_-_Gem",
    triangles: 140,
    name: "Изумрудная",
    variant: "Цитрин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d18b3d",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-29.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-30",
    url: "models/stones/jw-stone-gem-30.glb",
    pack: "gem",
    index: 30,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_62",
    sourceMaterial: "Blue_-_Gem",
    triangles: 140,
    name: "Изумрудная",
    variant: "Сапфир",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#345caa",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-30.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-31",
    url: "models/stones/jw-stone-gem-31.glb",
    pack: "gem",
    index: 31,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_64",
    sourceMaterial: "Yellow_-_Gem",
    triangles: 140,
    name: "Изумрудная",
    variant: "Жёлтый топаз",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d9b351",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-31.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-32",
    url: "models/stones/jw-stone-gem-32.glb",
    pack: "gem",
    index: 32,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_66",
    sourceMaterial: "White_-_Gem",
    triangles: 140,
    name: "Изумрудная",
    variant: "Бесцветный",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-32.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-33",
    url: "models/stones/jw-stone-gem-33.glb",
    pack: "gem",
    index: 33,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_68",
    sourceMaterial: "White_-_Gem",
    triangles: 140,
    name: "Ашер",
    variant: "Бесцветный",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-33.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-34",
    url: "models/stones/jw-stone-gem-34.glb",
    pack: "gem",
    index: 34,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_70",
    sourceMaterial: "Light_Blue_-_Gem",
    triangles: 140,
    name: "Ашер",
    variant: "Аквамарин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8fcee3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-34.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-35",
    url: "models/stones/jw-stone-gem-35.glb",
    pack: "gem",
    index: 35,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_72",
    sourceMaterial: "Green_-_Gem",
    triangles: 140,
    name: "Ашер",
    variant: "Изумруд",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#2b886b",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-35.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-36",
    url: "models/stones/jw-stone-gem-36.glb",
    pack: "gem",
    index: 36,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_74",
    sourceMaterial: "Red_-_Gem",
    triangles: 140,
    name: "Ашер",
    variant: "Рубин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#a92445",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-36.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-37",
    url: "models/stones/jw-stone-gem-37.glb",
    pack: "gem",
    index: 37,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_76",
    sourceMaterial: "Purple_-_Gem",
    triangles: 140,
    name: "Ашер",
    variant: "Аметист",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8e66b3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-37.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-38",
    url: "models/stones/jw-stone-gem-38.glb",
    pack: "gem",
    index: 38,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_78",
    sourceMaterial: "Orange_-_Gem",
    triangles: 140,
    name: "Ашер",
    variant: "Цитрин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d18b3d",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-38.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-39",
    url: "models/stones/jw-stone-gem-39.glb",
    pack: "gem",
    index: 39,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_80",
    sourceMaterial: "Blue_-_Gem",
    triangles: 140,
    name: "Ашер",
    variant: "Сапфир",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#345caa",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-39.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-40",
    url: "models/stones/jw-stone-gem-40.glb",
    pack: "gem",
    index: 40,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_82",
    sourceMaterial: "Yellow_-_Gem",
    triangles: 140,
    name: "Ашер",
    variant: "Жёлтый топаз",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d9b351",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-40.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-41",
    url: "models/stones/jw-stone-gem-41.glb",
    pack: "gem",
    index: 41,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_84",
    sourceMaterial: "White_-_Gem",
    triangles: 198,
    name: "Сердце",
    variant: "Бесцветный",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-41.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-42",
    url: "models/stones/jw-stone-gem-42.glb",
    pack: "gem",
    index: 42,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_86",
    sourceMaterial: "Light_Blue_-_Gem",
    triangles: 198,
    name: "Сердце",
    variant: "Аквамарин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8fcee3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-42.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-43",
    url: "models/stones/jw-stone-gem-43.glb",
    pack: "gem",
    index: 43,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_88",
    sourceMaterial: "Green_-_Gem",
    triangles: 198,
    name: "Сердце",
    variant: "Изумруд",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#2b886b",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-43.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-44",
    url: "models/stones/jw-stone-gem-44.glb",
    pack: "gem",
    index: 44,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_90",
    sourceMaterial: "Red_-_Gem",
    triangles: 198,
    name: "Сердце",
    variant: "Рубин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#a92445",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-44.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-45",
    url: "models/stones/jw-stone-gem-45.glb",
    pack: "gem",
    index: 45,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_92",
    sourceMaterial: "Purple_-_Gem",
    triangles: 198,
    name: "Сердце",
    variant: "Аметист",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8e66b3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-45.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-46",
    url: "models/stones/jw-stone-gem-46.glb",
    pack: "gem",
    index: 46,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_94",
    sourceMaterial: "Orange_-_Gem",
    triangles: 198,
    name: "Сердце",
    variant: "Цитрин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d18b3d",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-46.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-47",
    url: "models/stones/jw-stone-gem-47.glb",
    pack: "gem",
    index: 47,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_96",
    sourceMaterial: "Blue_-_Gem",
    triangles: 198,
    name: "Сердце",
    variant: "Сапфир",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#345caa",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-47.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-48",
    url: "models/stones/jw-stone-gem-48.glb",
    pack: "gem",
    index: 48,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_98",
    sourceMaterial: "Yellow_-_Gem",
    triangles: 198,
    name: "Сердце",
    variant: "Жёлтый топаз",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d9b351",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-48.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-49",
    url: "models/stones/jw-stone-gem-49.glb",
    pack: "gem",
    index: 49,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_100",
    sourceMaterial: "White_-_Gem",
    triangles: 302,
    name: "Маркиз",
    variant: "Бесцветный",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-49.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-50",
    url: "models/stones/jw-stone-gem-50.glb",
    pack: "gem",
    index: 50,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_102",
    sourceMaterial: "Light_Blue_-_Gem",
    triangles: 302,
    name: "Маркиз",
    variant: "Аквамарин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8fcee3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-50.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-51",
    url: "models/stones/jw-stone-gem-51.glb",
    pack: "gem",
    index: 51,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_104",
    sourceMaterial: "Green_-_Gem",
    triangles: 302,
    name: "Маркиз",
    variant: "Изумруд",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#2b886b",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-51.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-52",
    url: "models/stones/jw-stone-gem-52.glb",
    pack: "gem",
    index: 52,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_106",
    sourceMaterial: "Red_-_Gem",
    triangles: 302,
    name: "Маркиз",
    variant: "Рубин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#a92445",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-52.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-53",
    url: "models/stones/jw-stone-gem-53.glb",
    pack: "gem",
    index: 53,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_108",
    sourceMaterial: "Purple_-_Gem",
    triangles: 302,
    name: "Маркиз",
    variant: "Аметист",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8e66b3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-53.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-54",
    url: "models/stones/jw-stone-gem-54.glb",
    pack: "gem",
    index: 54,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_110",
    sourceMaterial: "Orange_-_Gem",
    triangles: 302,
    name: "Маркиз",
    variant: "Цитрин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d18b3d",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-54.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-55",
    url: "models/stones/jw-stone-gem-55.glb",
    pack: "gem",
    index: 55,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_112",
    sourceMaterial: "Blue_-_Gem",
    triangles: 302,
    name: "Маркиз",
    variant: "Сапфир",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#345caa",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-55.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-56",
    url: "models/stones/jw-stone-gem-56.glb",
    pack: "gem",
    index: 56,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_114",
    sourceMaterial: "Yellow_-_Gem",
    triangles: 302,
    name: "Маркиз",
    variant: "Жёлтый топаз",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d9b351",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-56.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-57",
    url: "models/stones/jw-stone-gem-57.glb",
    pack: "gem",
    index: 57,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_116",
    sourceMaterial: "White_-_Gem",
    triangles: 384,
    name: "Овал",
    variant: "Бесцветный",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-57.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-58",
    url: "models/stones/jw-stone-gem-58.glb",
    pack: "gem",
    index: 58,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_118",
    sourceMaterial: "Light_Blue_-_Gem",
    triangles: 384,
    name: "Овал",
    variant: "Аквамарин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8fcee3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-58.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-59",
    url: "models/stones/jw-stone-gem-59.glb",
    pack: "gem",
    index: 59,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_120",
    sourceMaterial: "Green_-_Gem",
    triangles: 384,
    name: "Овал",
    variant: "Изумруд",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#2b886b",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-59.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-60",
    url: "models/stones/jw-stone-gem-60.glb",
    pack: "gem",
    index: 60,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_122",
    sourceMaterial: "Red_-_Gem",
    triangles: 384,
    name: "Овал",
    variant: "Рубин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#a92445",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-60.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-61",
    url: "models/stones/jw-stone-gem-61.glb",
    pack: "gem",
    index: 61,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_124",
    sourceMaterial: "Purple_-_Gem",
    triangles: 384,
    name: "Овал",
    variant: "Аметист",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8e66b3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-61.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-62",
    url: "models/stones/jw-stone-gem-62.glb",
    pack: "gem",
    index: 62,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_126",
    sourceMaterial: "Orange_-_Gem",
    triangles: 384,
    name: "Овал",
    variant: "Цитрин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d18b3d",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-62.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-63",
    url: "models/stones/jw-stone-gem-63.glb",
    pack: "gem",
    index: 63,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_128",
    sourceMaterial: "Blue_-_Gem",
    triangles: 384,
    name: "Овал",
    variant: "Сапфир",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#345caa",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-63.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-64",
    url: "models/stones/jw-stone-gem-64.glb",
    pack: "gem",
    index: 64,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_130",
    sourceMaterial: "Yellow_-_Gem",
    triangles: 384,
    name: "Овал",
    variant: "Жёлтый топаз",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d9b351",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-64.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-65",
    url: "models/stones/jw-stone-gem-65.glb",
    pack: "gem",
    index: 65,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_132",
    sourceMaterial: "White_-_Gem",
    triangles: 302,
    name: "Груша",
    variant: "Бесцветный",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-65.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-66",
    url: "models/stones/jw-stone-gem-66.glb",
    pack: "gem",
    index: 66,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_134",
    sourceMaterial: "Light_Blue_-_Gem",
    triangles: 302,
    name: "Груша",
    variant: "Аквамарин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8fcee3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-66.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-67",
    url: "models/stones/jw-stone-gem-67.glb",
    pack: "gem",
    index: 67,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_136",
    sourceMaterial: "Green_-_Gem",
    triangles: 302,
    name: "Груша",
    variant: "Изумруд",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#2b886b",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-67.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-68",
    url: "models/stones/jw-stone-gem-68.glb",
    pack: "gem",
    index: 68,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_138",
    sourceMaterial: "Red_-_Gem",
    triangles: 302,
    name: "Груша",
    variant: "Рубин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#a92445",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-68.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-69",
    url: "models/stones/jw-stone-gem-69.glb",
    pack: "gem",
    index: 69,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_140",
    sourceMaterial: "Purple_-_Gem",
    triangles: 302,
    name: "Груша",
    variant: "Аметист",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8e66b3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-69.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-70",
    url: "models/stones/jw-stone-gem-70.glb",
    pack: "gem",
    index: 70,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_142",
    sourceMaterial: "Orange_-_Gem",
    triangles: 302,
    name: "Груша",
    variant: "Цитрин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d18b3d",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-70.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-71",
    url: "models/stones/jw-stone-gem-71.glb",
    pack: "gem",
    index: 71,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_144",
    sourceMaterial: "Blue_-_Gem",
    triangles: 302,
    name: "Груша",
    variant: "Сапфир",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#345caa",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-71.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-72",
    url: "models/stones/jw-stone-gem-72.glb",
    pack: "gem",
    index: 72,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_146",
    sourceMaterial: "Yellow_-_Gem",
    triangles: 302,
    name: "Груша",
    variant: "Жёлтый топаз",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d9b351",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-72.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-73",
    url: "models/stones/jw-stone-gem-73.glb",
    pack: "gem",
    index: 73,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_148",
    sourceMaterial: "Light_Blue_-_Gem",
    triangles: 64,
    name: "Радиант",
    variant: "Аквамарин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8fcee3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-73.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-74",
    url: "models/stones/jw-stone-gem-74.glb",
    pack: "gem",
    index: 74,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_150",
    sourceMaterial: "Green_-_Gem",
    triangles: 64,
    name: "Радиант",
    variant: "Изумруд",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#2b886b",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-74.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-75",
    url: "models/stones/jw-stone-gem-75.glb",
    pack: "gem",
    index: 75,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_152",
    sourceMaterial: "Red_-_Gem",
    triangles: 64,
    name: "Радиант",
    variant: "Рубин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#a92445",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-75.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-76",
    url: "models/stones/jw-stone-gem-76.glb",
    pack: "gem",
    index: 76,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_154",
    sourceMaterial: "Purple_-_Gem",
    triangles: 64,
    name: "Радиант",
    variant: "Аметист",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8e66b3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-76.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-77",
    url: "models/stones/jw-stone-gem-77.glb",
    pack: "gem",
    index: 77,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_156",
    sourceMaterial: "Orange_-_Gem",
    triangles: 64,
    name: "Радиант",
    variant: "Цитрин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d18b3d",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-77.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-78",
    url: "models/stones/jw-stone-gem-78.glb",
    pack: "gem",
    index: 78,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_158",
    sourceMaterial: "Yellow_-_Gem",
    triangles: 64,
    name: "Радиант",
    variant: "Жёлтый топаз",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d9b351",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-78.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-79",
    url: "models/stones/jw-stone-gem-79.glb",
    pack: "gem",
    index: 79,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_160",
    sourceMaterial: "Blue_-_Gem",
    triangles: 64,
    name: "Радиант",
    variant: "Сапфир",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#345caa",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-79.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-80",
    url: "models/stones/jw-stone-gem-80.glb",
    pack: "gem",
    index: 80,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_162",
    sourceMaterial: "White_-_Gem",
    triangles: 64,
    name: "Радиант",
    variant: "Бесцветный",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-80.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-81",
    url: "models/stones/jw-stone-gem-81.glb",
    pack: "gem",
    index: 81,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_164",
    sourceMaterial: "Light_Blue_-_Gem",
    triangles: 60,
    name: "Принцесса",
    variant: "Аквамарин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8fcee3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-81.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-82",
    url: "models/stones/jw-stone-gem-82.glb",
    pack: "gem",
    index: 82,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_166",
    sourceMaterial: "White_-_Gem",
    triangles: 60,
    name: "Принцесса",
    variant: "Бесцветный",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#e6edf0",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-82.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-83",
    url: "models/stones/jw-stone-gem-83.glb",
    pack: "gem",
    index: 83,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_168",
    sourceMaterial: "Green_-_Gem",
    triangles: 60,
    name: "Принцесса",
    variant: "Изумруд",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#2b886b",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-83.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-84",
    url: "models/stones/jw-stone-gem-84.glb",
    pack: "gem",
    index: 84,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_170",
    sourceMaterial: "Red_-_Gem",
    triangles: 60,
    name: "Принцесса",
    variant: "Рубин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#a92445",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-84.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-85",
    url: "models/stones/jw-stone-gem-85.glb",
    pack: "gem",
    index: 85,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_172",
    sourceMaterial: "Purple_-_Gem",
    triangles: 60,
    name: "Принцесса",
    variant: "Аметист",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#8e66b3",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-85.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-86",
    url: "models/stones/jw-stone-gem-86.glb",
    pack: "gem",
    index: 86,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_174",
    sourceMaterial: "Orange_-_Gem",
    triangles: 60,
    name: "Принцесса",
    variant: "Цитрин",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d18b3d",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-86.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-87",
    url: "models/stones/jw-stone-gem-87.glb",
    pack: "gem",
    index: 87,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_176",
    sourceMaterial: "Blue_-_Gem",
    triangles: 60,
    name: "Принцесса",
    variant: "Сапфир",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#345caa",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-87.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
  {
    id: "jw-stone-gem-88",
    url: "models/stones/jw-stone-gem-88.glb",
    pack: "gem",
    index: 88,
    sourceFile: "gemstone_pack.glb",
    sourceNode: "Object_178",
    sourceMaterial: "Yellow_-_Gem",
    triangles: 60,
    name: "Принцесса",
    variant: "Жёлтый топаз",
    project: "jewelry",
    category: "stone",
    role: "stone",
    size: 1,
    color: "#d9b351",
    price: 65,
    thumbnail: "thumbnails/jw-stone-gem-88.jpg",
    face: "y",
    source: "jw-stone/gemstone_pack.glb",
  },
];
export const byId = Object.fromEntries(catalogue.map((a) => [a.id, a]));
