"""Curated domain data: published structures, distinct from renderer calibration.

Source descriptions are short factual notes, not copied recipe instructions.
Dimensions explicitly distinguish published measurements and our visual ranges.
Run before editing geometry: the resulting records drive selection and assembly.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / 'shared' / 'domain'
ROOT.mkdir(parents=True, exist_ok=True)
sources = {}
def source(id, title, url, facts):
    sources[id] = dict(id=id, title=title, url=url, accessed='2026-10-07', facts=facts)

source('cal-cheese', 'Callebaut: Caramel cheesecake', 'https://www.callebaut.com/en/recipes/caramel-cheesecake/2132', 'Breton biscuit, caramel cream-cheese filling, salted caramel, gold-chocolate glaze; biscuit rolled to 4 mm.')
source('cal-rasp', 'Callebaut: Kumabo raspberry mousse pastry', 'https://www.callebaut.com/en/recipes/kumabo-chocolate-mousse-raspberry/1133', 'Chocolate sablé supports chocolate mousse; finish includes fresh raspberries and macarons.')
source('cal-hazel', 'Callebaut: Hazelnut Crunch Entremet', 'https://www.callebaut.com/en-US/recipes/Hazelnut-Crunch-Entremet/3601', 'Hazelnut biscuit, chocolate-hazelnut crunch, gianduja mousse, praline glaze; moulded and frozen before glazing.')
source('cal-charm', 'Callebaut: Raspberry chocolate charm', 'https://www.callebaut.com/en/recipes/rasberry-chocolate-charm/1212', 'Two sablé layers, raspberry chocolate crémeux, chocolate glaze, raspberry and pistachio accents.')
source('cal-paris', 'Callebaut: Ruby raspberry pistachio Paris-Brest', 'https://www.callebaut.com/en-CA/recipes/ruby-raspberry-pistachio-paris-brest/5097', 'Choux with ruby cream, raspberry and pistachio praline.')
source('kab-choux', 'King Arthur: Cream puffs and éclairs', 'https://www.kingarthurbaking.com/recipes/cream-puffs-and-eclairs-recipe', 'Choux geometry differs for round puffs and elongated éclairs; pastry-cream filling and chocolate top icing.')
source('kab-lemon', 'King Arthur: Lemon Cloud Cake', 'https://www.kingarthurbaking.com/recipes/lemon-cloud-cake-recipe', 'Two cake layers, lemon pastry cream and whipped lemon cream; 8-inch square or 9-inch round pans.')
source('kab-forest', 'King Arthur: Black Forest Cake', 'https://www.kingarthurbaking.com/recipes/black-forest-cake-recipe', 'Chocolate cake, cherry filling, whipped cream and chocolate decoration.')
source('kab-tiramisu', 'King Arthur: Tiramisu', 'https://www.kingarthurbaking.com/recipes/tiramisu-recipe', 'Coffee-soaked sponge or ladyfingers alternate with mascarpone filling.')
source('mdc-opera', 'Meilleur du Chef: CAP Opéra', 'https://www.meilleurduchef.com/fr/recette/biscuit-joconde-opera-cap-patissier-video.html', 'Almond Joconde, coffee syrup, coffee buttercream and chocolate ganache form thin alternating layers.')
source('mdc-fraisier', 'Meilleur du Chef: Fraisier', 'https://www.meilleurduchef.com/fr/recette/fraisier-facile.html', 'Génoise, mousseline, strawberries and almond-paste finish.')
source('cap-fraisier', 'French CAP pastry examination: Fraisier', 'https://bnseep.eduscol.education.fr/ressources/examens/sujets/13/400/2210500/E2/U21_sujet2.pdf', 'Published 20 cm diameter and 4.5 cm ring height; génoise, mousseline, strawberries, optional kirsch syrup.')
source('laf-love', 'LaFuong: Roll in Love', 'https://lafuong.com/roll-in-love', '14 cm heart, 5 cm tall; chocolate sponge, vanilla crémeux, wild-strawberry jam, chocolate mousse, mirror glaze.')
source('lad-macaron', 'Ladurée: macaron flavours', 'https://laduree.com/en/pages/macarons-flavors', 'Almond shells; distinct chocolate ganache, raspberry jam, pistachio buttercream, vanilla cream and salted-caramel fillings.')
source('wil-mini', 'Wilton: Mini yellow cakes', 'https://wilton.com/mini-yellow-cakes/wlrecip-8899/', 'Small layer cakes use buttercream and sprinkles.')
source('wil-stack', 'Wilton: tier construction', 'https://wilton.com/stacked-tiered-cake-construction/wltech-423/', 'Separate cake boards and cut support dowels carry upper tiers; stacking is a structural system.')
source('ifl-method', 'Interflora: hand-tied and container arrangements', 'https://www.interflora.co.uk/page/designed-for-you', 'Hand-tied bouquets use a loose spiral; container arrangements use floral foam; hatboxes are filled with blooms.')
source('ifl-season', 'Interflora: seasonal flowers', 'https://www.interflora.co.uk/blog/flower-guides/best-flowers-for-every-month', 'Seasonality refers to UK outdoor production, rather than guaranteed local or imported availability.')
source('ifl-species', 'Interflora: flower guide', 'https://www.interflora.co.uk/blog/flower-guides', 'Species have distinct forms; spring tulips, summer peonies and autumn chrysanthemums are differentiated.')
source('ifl-peony', 'Interflora: peony guide', 'https://www.interflora.co.uk/blog/flower-guides/peony', 'Peonies are large focal blooms; garden roses, hydrangeas and dahlias are alternatives outside their season.')
source('ifl-spring', 'Interflora: spring wedding flowers', 'https://www.interflora.co.uk/blog/occasions/wedding/spring-wedding-flowers', 'Spring examples include anemones, ranunculus, tulips, peonies, sweet peas, hyacinths, lilac and muscari.')
source('da-taffeta', 'David Austin: Pink Taffeta', 'https://www.davidaustinrosebouquets.com/products/pink-taffeta', 'Keira roses with Ranunculus Elegance Rosa and Anemone Mistral Panda Blush; mixed blooms grouped around roses.')
source('da-winter', 'David Austin: winter bouquets', 'https://www.davidaustin.com/5-winter-wedding-bouquets/', 'Leonora roses combined with ranunculus, lilac, astrantia, hellebore and trailing foliage.')
source('da-summer', 'David Austin: summer bridal bouquets', 'https://www.davidaustin.com/summer-2023-wedding-bouquet-trends/', 'Ivory garden roses with yellow butterfly ranunculus form loose, directional bouquets.')
source('gia-set', 'GIA: engagement-ring settings', 'https://4cs.gia.edu/en-us/blog/tips-for-buying-an-engagement-ring/', 'Solitaire, prong, bezel and halo constructions differ in how they support the centre and melee stones.')
source('gia-bearing', 'GIA: prong quality benchmarks', 'https://www.gia.edu/gia-website/bench-tip-avoid-stone-loss-with-quality-assurance-benchmarks', 'Prong bearings match stone contour without gaps; prong contact is a structural constraint.')
source('stuller-set', 'Stuller: wedding-band constructions', 'https://www.stuller.com/diamond-wedding-band-resource-center', 'Channel walls carry adjacent stones; bezel surrounds girdle; shared prongs retain two neighbouring stones.')
source('node-trudy', 'Nodeform: Trudy bezel trilogy', 'https://nodeform.com/products/trudy-three-stone-engagement-ring-bezel-set-round-moissanite-trillion-side-accents', '7 mm centre with 3×3 mm trillion sides; band 4.9 mm, bottom thickness 1.8 mm, shoulder 2.1 mm; height 5.4 mm.')
source('node-bypass', 'Nodeform: alexandrite bypass solitaire', 'https://nodeform.com/products/lab-alexandrite-bezel-bypass-solitaire-engagement-ring', 'Bypass shoulders join an encircling bezel; multiple precious-metal options.')
source('tif-pendant', 'Tiffany: bezel diamond pendant', 'https://www.tiffany.com/jewelry/necklaces-pendants/ep-diamonds-by-the-yard-platinum-round-brilliant-diamonds-necklaces-pendants-1428528852.html', 'Fine chain connected to a bezel-set diamond in platinum.')
source('tif-catalogue', 'Tiffany: engagement catalogue', 'https://media.tiffany.com/is/content/Tiffany/2018_Believe_In_Love_INTL', 'Solitaire, pavé, halo and graduated three-stone arrangements with round, oval, emerald and baguette cuts.')
source('cartier-trinity', 'Cartier: Trinity construction', 'https://www.cartier.com/en-us/jewelry/rings/trinity/', 'Three separate interlinked mobile bands use yellow, white and rose gold.')
source('rio-chain', 'Rio Grande: chain construction guide', 'https://products.riogrande.com/content/Instruction-Sheets/Guide-To-Jewelery-Chain-IS.pdf', 'Cable links alternate planes; curb links twist flat; Figaro repeats a long link with three to five short links; anchor adds a crossbar.')
source('rio-clasp', 'Rio Grande: clasps', 'https://www.riogrande.com/product/findings/clasps/', 'Lobster and ring clasps connect to jump rings and chain end fittings.')
for id, label in [('diamond','Бриллиант'),('ruby','Рубин'),('emerald','Изумруд'),('aquamarine','Аквамарин'),('amethyst','Аметист'),('opal','Опал')]:
    source('gia-'+id, 'GIA: '+label, 'https://www.gia.edu/'+id, 'Mineral identity and optical properties from the GIA gem encyclopedia.')

materials = []
def mat(id, name, color, roughness, micro, **kw):
    materials.append(dict(id=id,name=name,color=color,roughness=roughness,microstructure=micro,
                         calibration='PBR appearance tuning; roughness is not a laboratory measurement', **kw))
for id,name,color in [('yellow-gold','Жёлтое золото 750','#d8b56b'),('white-gold','Белое золото 750','#e0ded3'),('rose-gold','Розовое золото 750','#d79e88'),('silver','Серебро 925','#e7e9eb'),('platinum','Платина 950','#c9d0d5')]:
    mat(id,name,color,.16,'fine parallel polishing marks',metalness=1,finish=['polished','satin','brushed','hammered'],sources=['node-trudy','tif-pendant','cartier-trinity'])
for id,name,color,ior in [('diamond','Бриллиант','#ffffff',2.42),('ruby','Рубин','#b71f3e',1.766),('emerald','Изумруд','#12845c',1.58),('aquamarine','Аквамарин','#97d4e2',1.58),('amethyst','Аметист','#8552aa',1.548),('opal','Опал','#eee9d3',1.45)]:
    mat(id,name,color,.04,'facets' if id!='opal' else 'domed silica play-of-colour',metalness=0,ior=ior,transmission=.92 if id!='opal' else .12,sources=['gia-'+id])
foodmats=[('sponge','Бисквит','#dab77f',.86,'open irregular crumb pores'),('cocoa-sponge','Шоколадный бисквит','#694031',.88,'open crumb pores'),('sable','Песочное тесто','#c49555',.8,'baked fine granular crumb'),('joconde','Joconde','#d5b17c',.78,'fine almond crumb'),('choux','Заварное тесто','#c38a47',.66,'baked ridges and browned edges'),('cream','Сливочный крем','#fff0d4',.48,'whipped microbubbles'),('mousse','Мусс','#8c5c47',.52,'fine airy pores'),('custard','Заварной крем','#f1d7a1',.4,'smooth viscous surface'),('cheesecake','Сырный слой','#f3dfb9',.52,'fine dense grain'),('confit','Ягодное конфи','#a32946',.25,'fruit pulp and seeds'),('lemon-curd','Лимонный курд','#dfbe51',.3,'smooth opaque emulsion'),('dark-chocolate','Тёмный шоколад','#3e241c',.29,'fine cocoa surface'),('milk-chocolate','Молочный шоколад','#78503a',.31,'fine cocoa surface'),('white-chocolate','Белый шоколад','#e9d8ad',.32,'fine cocoa-butter surface'),('ganache','Ганаш','#513227',.26,'smooth emulsion'),('mirror-glaze','Зеркальная глазурь','#652b26',.13,'thin glossy meniscus'),('caramel','Карамель','#b87832',.18,'viscous translucent gloss'),('velvet','Шоколадный велюр','#b16b70',.92,'dense fine cocoa-butter droplets'),('fondant','Мастика','#f0e6d9',.7,'smooth sugar paste'),('nut','Орех','#ad8151',.77,'irregular toasted ridges'),('strawberry','Клубника','#bc3028',.41,'seeds in dimples'),('blueberry','Голубика','#415473',.72,'waxy bloom'),('raspberry','Малина','#b93549',.57,'individual drupelets'),('cherry','Вишня','#921f36',.25,'taut glossy skin')]
for id,name,color,r,micro in foodmats:mat(id,name,color,r,micro,metalness=0,subsurfaceApproximation='low transmission/backlighting only; not a spectral BSSRDF',sources=['cal-cheese','cal-hazel','kab-choux','lad-macaron'])
for id,name,color,r,micro in [('petal','Лепесток','#dbafbb',.63,'veins and thin translucent margins'),('leaf','Лист','#416c47',.61,'raised vein network'),('stem','Стебель','#507346',.75,'longitudinal fibres'),('kraft','Крафтовая бумага','#bda07a',.91,'cellulose fibres'),('tissue','Тишью','#eadbd5',.83,'fine creased fibres'),('mesh-wrap','Флористическая сетка','#d4c4b2',.72,'woven open grid'),('satin','Атласная лента','#b88796',.39,'directional satin weave'),('linen','Льняная лента','#c5b396',.9,'coarse woven fibres'),('rattan','Ротанг','#98774f',.84,'woven woody strips'),('glass','Стекло','#ffffff',.065,'smooth glass',)]:
    mat(id,name,color,r,micro,metalness=0,transmission=.97 if id=='glass' else .12 if id in ['petal','tissue'] else 0,sources=['ifl-method','da-taffeta'])

baking=[]
def food(id,name,role,material,geometry,refs,**kw):
    baking.append(dict(id=id,name=name,role=role,material=material,geometry=geometry,sources=refs,**kw))
for id,name,material in [('vanilla-sponge','Ванильный бисквит','sponge'),('cocoa-sponge','Шоколадный бисквит','cocoa-sponge'),('almond-joconde','Миндальный Joconde','joconde'),('hazelnut-biscuit','Фундучный бисквит','joconde'),('breton-sable','Бретонское песочное тесто','sable'),('chocolate-sable','Шоколадное песочное тесто','cocoa-sponge'),('choux-shell','Заварная оболочка','choux'),('ladyfinger','Савоярди','sponge'),('almond-shell','Миндальная оболочка макарона','joconde')]:
    food(id,name,'structure',material,'porous-layer' if id not in ['choux-shell','ladyfinger','almond-shell'] else id,['kab-choux','mdc-opera','cal-cheese','lad-macaron'],thicknessCm=[.35,2.1],dimensionBasis='renderer range, selected by recipe')
for id,name,material in [('vanilla-pastry-cream','Ванильный заварной крем','custard'),('mousseline','Крем-муслин','cream'),('diplomat','Крем-дипломат','cream'),('chantilly','Шантильи','cream'),('mascarpone','Крем маскарпоне','cream'),('vanilla-buttercream','Ванильный масляный крем','cream'),('coffee-buttercream','Кофейный масляный крем','cream'),('pistachio-buttercream','Фисташковый масляный крем','cream'),('dark-ganache','Тёмный ганаш','ganache'),('milk-ganache','Молочный ганаш','milk-chocolate'),('vanilla-cremeux','Ванильный кремё','custard'),('raspberry-cremeux','Малиново-шоколадный кремё','confit'),('chocolate-mousse','Шоколадный мусс','mousse'),('gianduja-mousse','Мусс джандуйя','mousse'),('caramel-cheese','Карамельный сырный слой','cheesecake'),('lemon-cream','Лимонный сливочный крем','cream')]:
    food(id,name,'cream',material,'emulsion-layer',['kab-choux','mdc-fraisier','kab-tiramisu','cal-hazel','cal-charm','lad-macaron','kab-lemon'],thicknessCm=[.25,2.8],dimensionBasis='renderer range, not copied recipe yield')
for id,name,material in [('strawberry-confit','Клубничное конфи','confit'),('raspberry-confit','Малиновое конфи','confit'),('cherry-compote','Вишнёвая начинка','confit'),('lemon-curd','Лимонный курд','lemon-curd'),('salted-caramel','Солёная карамель','caramel'),('hazelnut-praline','Фундучное пралине','nut'),('pistachio-praline','Фисташковое пралине','nut'),('chocolate-crunch','Шоколадный хрустящий слой','dark-chocolate'),('coffee-syrup','Кофейная пропитка','caramel')]:
    food(id,name,'insert',material,'thin-insert',['laf-love','cal-hazel','cal-paris','kab-forest','mdc-opera','kab-lemon'],thicknessCm=[.08,.55],dimensionBasis='renderer range')
for id,name,material in [('cream-coat','Сливочное покрытие','cream'),('ganache-coat','Ганаш','ganache'),('dark-mirror','Тёмная зеркальная глазурь','mirror-glaze'),('caramel-glaze','Карамельная глазурь','caramel'),('praline-glaze','Глазурь пралине','caramel'),('chocolate-velvet','Шоколадный велюр','velvet'),('almond-paste','Миндальная паста','fondant'),('sugar-fondant','Сахарная мастика','fondant'),('cocoa-dust','Какао','cocoa-sponge')]:
    food(id,name,'finish',material,'conformal-shell',['cal-cheese','cal-hazel','mdc-fraisier','kab-tiramisu','wil-stack'],thicknessCm=[.015,.3],dimensionBasis='renderer range')
native_decor=[('strawberry','Клубника','strawberry',3.8,'bk-berry-strawberry'),('blueberry','Голубика','blueberry',1.05,'bk-berry-blueberry'),('raspberry','Малина','raspberry',1.9,'bk-berry-raspberry'),('blackberry','Ежевика','raspberry',2.3,'bk-berry-blackberry'),('cherry','Вишня','cherry',2.5,'bk-berry-cherry'),('macaron','Макарон','joconde',4.2,'bk-decor-macaron'),('cream-rosette','Кремовая розетка','cream',3,'bk-decor-cream-rosette'),('meringue','Меренга','cream',2.8,'bk-decor-meringue-kiss'),('truffle','Трюфель','dark-chocolate',2.7,'bk-decor-truffle-ball'),('crumb','Крошка','sable',.45,'bk-decor-crumble-cluster'),('chocolate-shard','Шоколадная пластинка','dark-chocolate',4.5,'bk-decor-chocolate-shard'),('wafer','Вафельная трубочка','sable',7.5,'bk-decor-wafer-roll')]
for id,name,m,size,asset in native_decor:food(id,name,'decor',m,'native-mesh',['cal-rasp','cal-charm','kab-forest'],sizeCm=size,asset=asset,dimensionBasis='visually calibrated natural size; not a manufacturer tolerance')
for id,name,m,g in [('pistachio-kernel','Фисташка','nut','split-kernel'),('hazelnut','Фундук','nut','ribbed-nut'),('almond-flake','Миндальный лепесток','nut','curved-flake'),('chocolate-curl','Шоколадная стружка','dark-chocolate','rolled-thin-shell'),('chocolate-pearl','Шоколадная жемчужина','dark-chocolate','small-coated-core'),('piped-shell','Кремовая ракушка','cream','star-nozzle-sweep'),('piped-rope','Кремовый канат','cream','twisted-nozzle-sweep'),('cream-dollop','Кремовая капля','cream','tapered-nozzle-sweep'),('strawberry-half','Половинка клубники','strawberry','cut-fruit'),('lemon-slice','Лимонный срез','lemon-curd','citrus-segments')]:
    food(id,name,'decor',m,g,['cal-charm','cal-hazel','kab-lemon','kab-forest'],dimensionBasis='renderer calibration')

recipes=[]
def recipe(id,name,type,layers,cover,deco,refs,diameter=20,height=6,shape='round',tiers=1,**kw):
    recipes.append(dict(id=id,name=name,type=type,shape=shape,diameterCm=diameter,heightCm=height,maxTiers=tiers,layers=[dict(component=c,thicknessCm=t) for c,t in layers],cover=cover,compatibleDecor=deco,incompatible=['non-edible-live-flowers','loose-metal-jewelry'],sources=refs,dimensions='renderer calibration unless publishedDimensions is present',**kw))
berry=['strawberry','raspberry','blueberry','cream-rosette','macaron','meringue']
choc=['chocolate-shard','chocolate-curl','truffle','hazelnut','pistachio-kernel','raspberry']
recipe('fraisier','Фрезье','fraisier',[('vanilla-sponge',.8),('mousseline',2.8),('vanilla-sponge',.8)],'almond-paste',['strawberry','strawberry-half','pistachio-kernel'],['mdc-fraisier','cap-fraisier'],height=4.5,publishedDimensions=dict(diameterCm=20,heightCm=4.5),edgeFruit='strawberry-half')
recipe('opera','Опера','opera',[('almond-joconde',.55),('coffee-buttercream',.5),('almond-joconde',.55),('dark-ganache',.45),('almond-joconde',.55),('coffee-buttercream',.5)],'ganache-coat',['chocolate-shard','chocolate-curl','chocolate-pearl'],['mdc-opera'],shape='rectangle',diameter=18,height=3.2,soak='coffee-syrup')
recipe('caramel-cheesecake','Карамельный чизкейк','cheesecake',[('breton-sable',.4),('caramel-cheese',4.4),('salted-caramel',.3)],'caramel-glaze',['hazelnut','pistachio-kernel','chocolate-curl','crumb'],['cal-cheese'],height=5.2,publishedDimensions=dict(baseThicknessCm=.4))
recipe('hazelnut-entremet','Фундук и джандуйя','entremet',[('chocolate-crunch',.35),('gianduja-mousse',1.6),('hazelnut-biscuit',.7),('gianduja-mousse',2.25)],'praline-glaze',['hazelnut','chocolate-shard','chocolate-pearl','crumb'],['cal-hazel'],diameter=21,height=5,publishedDimensions=dict(mouldDiameterCm=21))
recipe('raspberry-chocolate','Шоколад и малина','entremet',[('chocolate-sable',.4),('chocolate-mousse',3.8)],'ganache-coat',['raspberry','macaron','chocolate-shard'],['cal-rasp'],height=4.5)
recipe('raspberry-cremeux','Малиновый кремё','tart',[('breton-sable',.4),('raspberry-cremeux',2.1),('breton-sable',.3)],'dark-mirror',['raspberry','pistachio-kernel','chocolate-curl'],['cal-charm'],height=3)
recipe('chocolate-strawberry-heart','Шоколад, клубника и ваниль','entremet',[('cocoa-sponge',.6),('vanilla-cremeux',.9),('strawberry-confit',.4),('cocoa-sponge',.6),('chocolate-mousse',2.4)],'dark-mirror',['strawberry','strawberry-half','chocolate-curl'],['laf-love'],diameter=14,height=5,shape='heart',publishedDimensions=dict(diameterCm=14,heightCm=5))
recipe('black-forest','Шварцвальд','sponge',[('cocoa-sponge',1.5),('chantilly',.6),('cherry-compote',.3),('cocoa-sponge',1.5),('chantilly',.6),('cherry-compote',.3),('cocoa-sponge',1.5)],'cream-coat',['cherry','chocolate-curl','cream-rosette'],['kab-forest'],height=7)
recipe('lemon-cloud','Лимонное облако','sponge',[('vanilla-sponge',2),('vanilla-pastry-cream',.4),('lemon-curd',.3),('vanilla-sponge',2),('lemon-cream',.8)],'cream-coat',['lemon-slice','cream-dollop','meringue'],['kab-lemon'],diameter=22.86,height=6,publishedDimensions=dict(roundPanDiameterCm=22.86))
recipe('tiramisu','Тирамису','tiramisu',[('ladyfinger',1),('mascarpone',1.3),('ladyfinger',1),('mascarpone',1.3)],'cocoa-dust',['chocolate-curl'],['kab-tiramisu'],shape='rectangle',height=5,soak='coffee-syrup')
recipe('vanilla-celebration','Ванильный праздничный','sponge',[('vanilla-sponge',1.5),('vanilla-buttercream',.6),('vanilla-sponge',1.5),('vanilla-buttercream',.6),('vanilla-sponge',1.5)],'cream-coat',berry+['piped-shell','piped-rope'],['wil-mini','wil-stack'],height=7,tiers=3,supportSystem='boards-and-dowels')
recipe('mini-buttercream','Мини-торт с кремом','mini',[('vanilla-sponge',1.2),('vanilla-buttercream',.6),('vanilla-sponge',1.2)],'cream-coat',['cream-rosette','piped-shell','meringue','strawberry'],['wil-mini'],diameter=10,height=4)
recipe('vanilla-eclair','Эклер с ванильным кремом','eclair',[('choux-shell',1),('vanilla-pastry-cream',1)],'ganache-coat',['chocolate-pearl','chocolate-curl'],['kab-choux'],diameter=12,height=3,nativeBase='bk-pastry-eclair')
recipe('cream-puff','Профитроль','profiterole',[('choux-shell',1),('chantilly',1)],'ganache-coat',['chocolate-pearl','chocolate-curl'],['kab-choux'],diameter=4.5,height=4,nativeBase='bk-pastry-profiterole')
recipe('paris-brest','Пари-Брест: малина и фисташка','paris-brest',[('choux-shell',1),('pistachio-praline',.4),('chantilly',1),('raspberry-confit',.3)],'cream-coat',['raspberry','pistachio-kernel','almond-flake'],['cal-paris'],diameter=9,height=4)
for id,name,filling in [('chocolate','Шоколадный','dark-ganache'),('raspberry','Малиновый','raspberry-confit'),('pistachio','Фисташковый','pistachio-buttercream'),('vanilla','Ванильный','vanilla-pastry-cream'),('caramel','Карамельный','salted-caramel')]:
    recipe('macaron-'+id,'Макарон · '+name,'macaron',[('almond-shell',.8),(filling,.45),('almond-shell',.8)],None,[],['lad-macaron'],diameter=4.2,height=2.05)

plants=[]
def plant(id,name,role,form,size,season,refs,asset=None,**kw):
    plants.append(dict(id=id,name=name,role=role,morphology=form,headDiameterCm=size,season=season,seasonRegion='UK outdoor; greenhouse and imports differ',sources=refs,asset=asset,dimensions='visual modelling range, not a cultivar measurement',**kw))
fl=[('rose','Садовая роза','focal','cupped-rosette',7.2,'spring-summer','fl-flower-garden-rose'),('peony','Пион','focal','many-layered-cup',10,'late-spring-early-summer','fl-flower-peony'),('ranunculus','Ранункулюс','secondary','concentric-cupped-petals',6,'spring','fl-flower-ranunculus'),('anemone','Анемона','secondary','single-petal-black-centre',6.4,'spring','fl-flower-anemone'),('tulip','Тюльпан','line','six-petal-cup',4.6,'spring','fl-flower-tulip'),('chamomile','Ромашка','filler','white-rays-yellow-disc',4.1,'summer','fl-flower-chamomile'),('gerbera','Гербера','focal','multi-row-rays-disc',8,'summer','fl-flower-gerbera'),('chrysanthemum','Хризантема','focal','incurved-many-petals',6.5,'autumn','fl-flower-chrysanthemum'),('lisianthus','Эустома','secondary','ruffled-cup',6,'summer','fl-flower-eustoma'),('lily','Восточная лилия','line','six-recurved-tepals-stamens',10,'summer','fl-flower-lily'),('dahlia','Георгин','focal','overlapping-geometric-petals',10,'late-summer-autumn',None),('hydrangea','Гортензия','mass','cluster-four-sepal-florets',16,'summer-autumn',None),('carnation','Гвоздика','secondary','serrated-ruffled-petals',6,'summer',None),('sweet-pea','Душистый горошек','line','wing-standard-keel',4,'spring-summer',None),('hellebore','Морозник','secondary','five-sepal-open-cup',6,'winter-spring',None),('astrantia','Астранция','filler','star-bracts-tiny-cluster',2.4,'summer',None),('muscari','Мускари','line','dense-bell-raceme',1,'spring',None),('lilac','Сирень','filler','branched-four-petal-florets',1,'spring',None)]
for id,name,role,form,size,season,asset in fl:plant(id,name,role,form,size,season,['ifl-species','ifl-spring','ifl-peony','da-winter'],asset,naturalColors=['ivory','blush','burgundy'] if id not in ['chamomile','muscari','gerbera'] else ['white-yellow'] if id=='chamomile' else ['violet-blue'] if id=='muscari' else ['pink','yellow','orange'])
for id,name,form,asset in [('eucalyptus','Эвкалипт','opposite-round-leaves','fl-green-eucalyptus'),('ruscus','Рускус','pointed-alternate-cladodes','fl-green-ruscus'),('fern','Папоротник','pinnate-frond','fl-green-fern'),('salal','Салал','broad-leaf-branch','fl-green-salal'),('gypsophila','Гипсофила','branched-tiny-white-flowers','fl-fill-gypsophila'),('limonium','Лимониум','airy-small-flower-spray','fl-fill-limonium'),('lagurus','Лагурус','soft-oval-grass-heads','fl-fill-lagurus'),('wheat','Колосья','grain-ear','fl-fill-wheat'),('olive','Олива','opposite-narrow-leaves',None),('ivy','Плющ','trailing-lobed-leaves',None),('pittosporum','Питтоспорум','whorled-variegated-leaves',None),('spirea','Спирея','arching-flowering-branch',None)]:
    plant(id,name,'filler' if id in ['gypsophila','limonium','lagurus','wheat','spirea'] else 'foliage',form,1,'spring-summer' if id=='spirea' else 'conditioned-year-round',['ifl-method','da-winter'],asset,lengthCm=[25,55])
forms=[dict(id=id,name=name,shape=shape,density=density,stemSystem=stem,packaging=pack,sources=refs) for id,name,shape,density,stem,pack,refs in [
('round','Круглый букет','hemisphere',.82,'hand-tied-spiral',['paper','vase'],['ifl-method']),('garden','Садовый букет','asymmetric-dome',.63,'hand-tied-spiral',['paper','vase'],['da-taffeta','da-summer']),('bridal','Свадебный','compact-dome',.9,'hand-tied-spiral',['ribbon'],['da-taffeta']),('cascade','Каскадный','directional-cascade',.57,'wired-and-bound',['ribbon'],['da-winter']),('line','Вытянутый','directional-fan',.55,'hand-tied-spiral',['paper','vase'],['ifl-method']),('minimal','Минималистичный','loose-fan',.4,'hand-tied-spiral',['paper','vase'],['ifl-method']),('hatbox','Композиция в коробке','low-dome',.94,'floral-foam',['box'],['ifl-method']),('basket','Композиция в корзине','low-asymmetric-dome',.8,'floral-foam',['basket'],['ifl-method'])]]
bouquets=[]
for id,name,form,focal,secondary,filler,foliage,refs in [
('garden-pink','Розы, ранункулюсы и анемоны','garden',['rose'],['ranunculus','anemone'],[],['eucalyptus'],['da-taffeta']),('ivory-bridal','Светлый свадебный','bridal',['rose'],['ranunculus'],['gypsophila'],['ruscus'],['da-summer']),('spring-air','Весенний воздушный','garden',['ranunculus'],['anemone','hellebore'],['astrantia'],['eucalyptus'],['ifl-spring','da-winter']),('peony-mono','Монобукет пионов','round',['peony'],[],[],[],['ifl-peony']),('rose-mono','Монобукет садовых роз','round',['rose'],[],[],[],['da-taffeta']),('tulip-line','Весенние тюльпаны','line',['tulip'],[],[],['olive'],['ifl-spring']),('meadow','Полевой','garden',['chamomile'],['lisianthus'],['gypsophila'],['fern'],['ifl-method','ifl-species']),('autumn','Осенний','garden',['dahlia','chrysanthemum'],['gerbera'],['limonium'],['salal'],['ifl-season']),('white-box','Светлая коробка','hatbox',['rose'],['lisianthus','carnation'],['gypsophila'],['ruscus'],['ifl-method']),('summer-basket','Летняя корзина','basket',['peony'],['rose','lisianthus'],[],['salal'],['ifl-method','ifl-season']),('minimal-stems','Несколько выразительных стеблей','minimal',['tulip'],['sweet-pea'],[],[],['ifl-spring']),('bridal-cascade','Свадебный каскад','cascade',['rose'],['hellebore'],['astrantia'],['ivy'],['da-winter'])]:
    bouquets.append(dict(id=id,name=name,form=form,roles=dict(focal=focal,secondary=secondary,filler=filler,foliage=foliage),sources=refs,observedVsAdapted='species roles and construction observed; exact counts/layout calibrated for these assets',stemCounts=dict(small=11,medium=19,large=29),stemDirections='shared binding point or foam insertion; never independent floating heads',colorFamilies=['ivory','blush','seasonal-natural']))

jewelryComponents=[]
def jc(id,name,type,geometry,refs,**kw):jewelryComponents.append(dict(id=id,name=name,type=type,geometry=geometry,sources=refs,**kw))
for id,name,profile,w in [('court','Полукруглая шинка','round-court',2),('flat','Плоская шинка','rounded-flat',2.5),('knife','Шинка с ребром','knife-edge',2),('comfort','Комфортная шинка','comfort-fit',3),('wide','Широкая шинка','rounded-flat',4.9),('split','Раздвоенная шинка','split-shoulder',2),('taper','Суженная шинка','tapered-shoulder',2.2),('bypass','Обходная шинка','bypass',2.1)]:
    jc('band-'+id,name,'band','swept-profile',['gia-set','node-trudy','node-bypass','tif-catalogue'],profile=profile,widthMm=w,thicknessMm=1.7,dimensionBasis='published for wide band; calibrated range for others',requires=['closed-inner-ring'])
for id,name,count,contact in [('four-prong','Четыре крапана',4,'girdle-bearing'),('six-prong','Шесть крапанов',6,'girdle-bearing'),('v-prong','V-крапаны',3,'protected-tip-bearing'),('bezel','Глухая закрепка',0,'folded-girdle-rim'),('half-bezel','Полуглухая закрепка',0,'two-opposing-rims'),('halo','Ореол',4,'centre-prongs-and-melee'),('channel','Канал',0,'opposing-continuous-walls'),('shared-prong','Общие крапаны',2,'paired-girdle-bearings'),('pave','Паве',4,'small-girdle-beads')]:
    jc('setting-'+id,name,'setting','contour-and-bearing',['gia-bearing','stuller-set','gia-set'],prongs=count,contact=contact,stoneSizesMm=[1,8],requires=['girdle-supported','pavilion-clearance'],incompatible=['unsupported-floating-stone'])
for id,name,g in [('gallery','Галерея','open-support-rails'),('basket','Корзинка каста','curved-uprights-and-rail'),('bridge','Перемычка','arched-bridge'),('post','Штифт серьги','post-with-stop'),('butterfly','Замок-бабочка','folded-spring-back'),('ear-hook','Швенза','curved-wire-with-loop'),('hinge','Шарнир','interleaved-knuckles-and-pin'),('bail','Бейл подвески','closed-bail'),('jump-ring','Соединительное кольцо','closed-round-wire'),('lobster','Карабин','body-gate-pivot'),('spring-clasp','Шпрингель','spring-ring-with-gate'),('cable-link','Якорное звено','alternating-plane-oval'),('curb-link','Панцирное звено','twisted-flat-oval'),('figaro-link','Фигаро','one-long-three-short'),('anchor-link','Морское звено','oval-with-crossbar'),('tennis-link','Теннисное звено','articulated-stone-basket'),('separator','Разделитель','solid-connecting-bridge')]:
    jc(id,name,'connection',g,['rio-chain','rio-clasp','gia-bearing','tif-pendant'],dimensionBasis='calibrated physical geometry')
cuts=[]
for id,name,ratio,setting in [('round','Круглая',1,['four-prong','six-prong','bezel','halo']),('oval','Овал',1.4,['four-prong','six-prong','bezel','halo']),('cushion','Кушон',1.08,['four-prong','bezel','halo']),('princess','Принцесса',1,['four-prong','bezel']),('emerald','Изумрудная',1.4,['four-prong','bezel']),('baguette','Багет',2,['channel','bezel']),('pear','Груша',1.5,['v-prong','bezel','halo']),('marquise','Маркиз',2,['v-prong','bezel']),('heart','Сердце',1,['v-prong','bezel']),('trillion','Триллион',1,['v-prong','bezel']),('cabochon','Кабошон',1.2,['bezel'])]:
    cuts.append(dict(id=id,name=name,lengthWidthRatio=ratio,ratioBasis='visualization target; individual stones vary',supportedSettings=setting,crown='smooth-dome' if id=='cabochon' else 'faceted',pavilion='flat-seat' if id=='cabochon' else 'faceted-cone',sources=['gia-set','tif-catalogue','node-trudy']))
jewelPatterns=[]
for id,name,type,band,setting,cut,size,refs in [('solitaire','Солитер · шесть крапанов','ring','court','six-prong','round',6.5,['gia-set','tif-catalogue']),('oval-solitaire','Овальный солитер','ring','taper','four-prong','oval',7,['gia-set','tif-catalogue']),('bezel-ring','Кольцо с глухой закрепкой','ring','comfort','bezel','round',6,['gia-set']),('bypass-ring','Кольцо с обходной шинкой','ring','bypass','bezel','oval',6,['node-bypass']),('halo-ring','Кольцо с ореолом','ring','split','halo','cushion',6,['tif-catalogue']),('trilogy','Трилогия','ring','wide','bezel','round',7,['node-trudy']),('emerald-solitaire','Ступенчатая огранка','ring','flat','four-prong','emerald',7,['tif-catalogue']),('pear-solitaire','Груша с защитой острия','ring','taper','v-prong','pear',7,['gia-bearing','gia-set']),('channel-band','Кольцо с каналом','ring','flat','channel','baguette',2.6,['stuller-set']),('pave-band','Кольцо паве','ring','court','pave','round',1.3,['stuller-set']),('wedding-band','Обручальное кольцо','ring','comfort',None,None,0,['node-trudy']),('three-metal','Три переплетённые шинки','ring','court',None,None,0,['cartier-trinity']),('stud','Пусеты','earring',None,'four-prong','round',5,['gia-set']),('bezel-stud','Пусеты с глухой закрепкой','earring',None,'bezel','round',5,['tif-pendant']),('drop','Серьги-капли','earring',None,'v-prong','pear',7,['gia-bearing']),('hoop','Серьги-кольца','earring',None,None,None,0,['rio-clasp']),('bezel-pendant','Подвеска в глухой закрепке','pendant',None,'bezel','round',6,['tif-pendant']),('pear-pendant','Подвеска-капля','pendant',None,'v-prong','pear',8,['gia-bearing']),('cabochon-pendant','Кулон с кабошоном','pendant',None,'bezel','cabochon',9,['stuller-set']),('tennis','Теннисный браслет','bracelet',None,'four-prong','round',3,['stuller-set','rio-clasp']),('bangle','Жёсткий браслет','bracelet',None,None,None,0,['rio-clasp']),('cable-chain','Якорная цепочка','chain',None,None,None,0,['rio-chain','rio-clasp']),('curb-chain','Панцирная цепочка','chain',None,None,None,0,['rio-chain','rio-clasp']),('figaro-chain','Фигаро','chain',None,None,None,0,['rio-chain','rio-clasp'])]:
    jewelPatterns.append(dict(id=id,name=name,type=type,band=band,setting=setting,defaultCut=cut,stoneSizeMm=size,metals=['yellow-gold','white-gold','rose-gold','silver','platinum'],finishes=['polished','satin','brushed','hammered'],sources=refs,dimensions='renderer calibration except explicitly publishedMeasures',compatibleCuts=next((c['supportedSettings'] and [cc['id'] for cc in cuts if setting in cc['supportedSettings']] for c in cuts if c['id']==cut),[]) if cut else [],parts=['foundation','setting','stone','connections'],incompatible=['unseated-girdle','intersecting-inner-ring','unjoined-connection']))
next(p for p in jewelPatterns if p['id']=='trilogy')['publishedMeasures']=dict(centreMm=7,sidesMm=[3,3],bandWidthMm=4.9,bottomThicknessMm=1.8,heightMm=5.4)

# Link component provenance to recipes that actually use it, rather than assigning
# a broad list of unrelated recipes to every ingredient.
sources['cap-fraisier']['title'] = 'French Baccalaureat professionnel pastry examination, 2013: Fraisier'
for gem,name,color,ior in [('sapphire','Сапфир','#345caa',1.766),('citrine','Цитрин','#d18b3d',1.548),('topaz','Топаз','#d9b351',1.623)]:
    source('gia-'+gem,'GIA: '+name,'https://www.gia.edu/'+gem,'Published mineral refractive-index range; scalar IOR is its approximate midpoint.')
    mat(gem,name,color,.035,'polished facets',metalness=0,ior=ior,transmission=.92,sources=['gia-'+gem])
for pid,title,url,facts in [('rhs-hydrangea','RHS: Hydrangea macrophylla','https://www.rhs.org.uk/plants/40792/hydrangea-macrophylla-h/details','Mophead hydrangea has a clustered flower head.'),('rhs-dahlia','RHS: dahlia forms','https://www.rhs.org.uk/plants/dahlia/growing-guide','Cultivar classes include cactus, ball, collarette and other distinct ray-floret arrangements.'),('rhs-pea','RHS: annual sweet peas','https://www.rhs.org.uk/plants/lathyrus/sweet-peas','Pea-like flowers in white, pink, coral, red, violet and blue; individual plant stems used for cut flowers.')]:source(pid,title,url,facts)
for pid,ref in [('hydrangea','rhs-hydrangea'),('dahlia','rhs-dahlia'),('sweet-pea','rhs-pea')]:next(p for p in plants if p['id']==pid)['sources']=[ref]
source('kab-cupcakes','King Arthur: commercial cupcake constructions','https://www.kingarthurbaking.com/cupcakes','Tiramisu cupcakes use coffee-soaked vanilla cake with mascarpone frosting; Boston cream cupcakes use pastry cream and ganache.')
source('kab-doughnut','King Arthur: Baked Doughnuts Three Ways','https://www.kingarthurbaking.com/recipes/baked-doughnuts-three-ways-recipe','Baked ring doughnuts with sugar or thin icing; the central hole is preserved.')
source('kab-cookie','King Arthur: decorating cookies','https://www.kingarthurbaking.com/learn/guides/cookie-decorating','Cut-out cookies with thin sugar icing and small edible sprinkles.')
source('kab-brownie','King Arthur: Fudge Brownies','https://www.kingarthurbaking.com/recipes/fudge-brownies-recipe','Dense chocolate brownies with a crackled surface; published portion size 2 inches.')
source('cal-velvet','Callebaut Chocolate Academy: velvet temperature','https://www.callebaut.com/en-GB/callebaut-chocolate-academy/tutorials/velvet-temperature','Chocolate spray creates a fine textured velvet finish on chilled cakes and pastries.')
food('gold-leaf','Пищевое сусальное золото','decor','yellow-gold','native-mesh',['mdc-opera'],asset='bk-decor-gold-flake',sizeCm=.7)
next(r for r in recipes if r['id']=='opera')['compatibleDecor']+=['gold-leaf']
next(r for r in recipes if r['id']=='opera')['defaultDecor']=['gold-leaf','chocolate-pearl']
food('sugar-icing','Сахарная глазурь','finish','cream','thin-icing',['kab-cookie','kab-doughnut'])
food('brownie-crumb','Шоколадный брауни','structure','cocoa-sponge','dense-crumb',['kab-brownie'])
food('sugar-pearl','Сахарная жемчужина','decor','fondant','coated-core',['kab-cookie'],asset='bk-decor-sprinkle-ball',sizeCm=.35)
recipe('tiramisu-cupcake','Капкейк тирамису','cupcake',[('vanilla-sponge',3),('mascarpone',2)],'cocoa-dust',[],['kab-cupcakes'],diameter=7.5,height=5.5,nativeBase='bk-pastry-cupcake',soak='coffee-syrup')
recipe('vanilla-doughnut','Пончик с сахарной глазурью','donut',[('vanilla-sponge',2)],'sugar-icing',['sugar-pearl'],['kab-doughnut'],diameter=8,height=2.5,nativeBase='bk-pastry-donut')
for shape in ['round','heart']:recipe('iced-cookie-'+shape,'Сахарное печенье · '+('круг' if shape=='round' else 'сердце'),'cookie',[('breton-sable',.7)],'sugar-icing',['sugar-pearl'],['kab-cookie'],diameter=6.5,height=.9,shape=shape,nativeBase='bk-pastry-cookie-'+shape)
recipe('fudge-brownie','Шоколадный брауни','brownie',[('brownie-crumb',2.5)],None,[],['kab-brownie'],diameter=5.08,height=2.5,shape='rectangle',nativeBase='bk-pastry-brownie-bite',publishedDimensions=dict(portionCm=5.08))
next(r for r in recipes if r['id']=='hazelnut-entremet')['compatibleCovers']=['praline-glaze','chocolate-velvet']
for pid,cultivar in [('rose','Keira (Ausboxer), garden rose type'),('ranunculus','Elegance Rosa'),('anemone','Mistral Panda Blush')]:next(p for p in plants if p['id']==pid)['cultivarReference']=dict(name=cultivar,source='da-taffeta',geometry='species-level asset; cultivar-inspired palette, not an exact botanical scan')
for id,name in [('asscher','Ашер'),('step','Ступенчатая огранка')]:cuts.append(dict(id=id,name=name,lengthWidthRatio=1 if id=='asscher' else 1.35,ratioBasis='visualization target',supportedSettings=['four-prong','bezel'],crown='faceted-step',pavilion='faceted-cone',sources=['tif-catalogue','gia-set']))
source('luther-stack','Luthers Diamonds: three separate stacking bands','https://luthersdiamonds.com/products/triple-stacking-modular-band-ring-in-14k-yellow-rose-white-gold','Separate yellow, white and rose gold bands can be stacked or worn individually; no interpenetrating geometry is required.')
stack=next(p for p in jewelPatterns if p['id']=='three-metal');stack.update(name='Комплект трёх колец',sources=['luther-stack'],construction='three-separate-stacking-bands',fixedMetals=['yellow-gold','white-gold','rose-gold'])
source('tif-stud','Tiffany: Solitaire stud earrings','https://www.tiffany.com/jewelry/earrings/platinum-round-brilliant-diamonds-earrings-60006719.html','Round brilliant stones in metal baskets; matching pair of post earrings.')
source('tif-tennis','Tiffany: diamond tennis bracelets','https://www.tiffany.com/jewelry/tennis-bracelets/platinum/diamond/','Flexible line bracelets carry repeated round brilliant diamonds.')
source('tif-hoop','Tiffany: gold hoop earrings','https://www.tiffany.com/jewelry/hoop-earrings/gold/','Hoop earrings have a wearable closure rather than a decorative closed annulus.')
for pid,ref in [('stud','tif-stud'),('bezel-stud','tif-stud'),('tennis','tif-tennis'),('hoop','tif-hoop')]:next(p for p in jewelPatterns if p['id']==pid)['sources'].append(ref)
food('ruby-cream','Рубиновый крем','cream','cream','emulsion-layer',['cal-paris'])
next(r for r in recipes if r['id']=='paris-brest')['layers'][2]['component']='ruby-cream'
for component in baking:
    used=[r for r in recipes if component['id'] in [x['component'] for x in r['layers']]+r['compatibleDecor']+[r['cover'],r.get('soak')]+r.get('compatibleCovers',[])]
    component['compatibleRecipes']=[r['id'] for r in used]
    component['available']=bool(used)
    if used: component['sources']=sorted({ref for r in used for ref in r['sources']})
asset_corrections={'fl-flower-garden-rose':'fl-flower-rose-garden','fl-flower-peony':'fl-flower-peony-open','fl-flower-chrysanthemum':'fl-flower-chrysanthemum-spray','fl-flower-lily':'fl-flower-lily-oriental','fl-green-eucalyptus':'fl-green-eucalyptus-silver','fl-green-olive':'fl-green-olive-branch'}
asset_corrections.update({'fl-fill-lagurus':'fl-green-lagurus','fl-fill-limonium':None,'fl-fill-wheat':None})
natural={'rose':['ivory','blush','apricot','burgundy'],'peony':['ivory','blush','burgundy'],'ranunculus':['ivory','blush','yellow','orange'],'anemone':['ivory','pink','violet'],'tulip':['ivory','blush','yellow','burgundy'],'chrysanthemum':['ivory','yellow','burgundy'],'lisianthus':['ivory','blush','violet'],'lily':['ivory','pink'],'dahlia':['ivory','blush','yellow','burgundy'],'hydrangea':['ivory','blush','blue'],'carnation':['ivory','blush','burgundy'],'sweet-pea':['ivory','blush','violet'],'hellebore':['ivory','green','burgundy'],'astrantia':['ivory','blush'],'lilac':['ivory','violet']}
for p in plants:
    p['asset']=asset_corrections.get(p['asset'],p['asset'])
    if p['asset']=='fl-green-salal': p['asset']=None
    if p['id'] in natural:p['naturalColors']=natural[p['id']]
    p['compatibleBouquets']=[b['id'] for b in bouquets if any(p['id'] in members for members in b['roles'].values())]
    p['headDepthCalibration']={'rose':1.7,'ranunculus':1.4,'peony':1.25,'chrysanthemum':1.2}.get(p['id'],1)
for recipe in recipes:
    if recipe['id'] in ['fraisier','chocolate-strawberry-heart']:recipe['finishColor']={'fraisier':'#dfb5b4','chocolate-strawberry-heart':'#bb1738'}[recipe['id']]
for bouquet in bouquets:
    bouquet['defaultPalette']=1 if bouquet['id'] in ['ivory-bridal','white-box','bridal-cascade','meadow'] else 3 if bouquet['id']=='autumn' else 0
    if bouquet['form']=='minimal':bouquet['stemCounts']=dict(small=5,medium=7,large=9)
    elif bouquet['form']=='line':bouquet['stemCounts']=dict(small=5,medium=7,large=11)
source('rhs-astrantia','RHS: Astrantia major morphology','https://www.rhs.org.uk/plants/1870/astrantia-major/details','Branched upright stems carry compact umbels surrounded by conspicuous bracts; leaf shape and branching differ from a generic foliage spray.')
source('umich-sweetpea','University of Michigan: Lathyrus odoratus morphology','https://climbers.lsa.umich.edu/lathyrus-odoratus/','The pea flower has one standard, two wing petals and a keel formed by two joined petals; flowers occur in small groups.')
source('rhs-ivy','RHS: Hedera morphology','https://www.rhs.org.uk/plants/ivy/growing-guide','Ivy foliage varies by species and growth phase; lobed juvenile leaves are appropriate for a trailing ivy model.')
for pid,ref in [('astrantia','rhs-astrantia'),('sweet-pea','umich-sweetpea'),('ivy','rhs-ivy')]:next(p for p in plants if p['id']==pid)['sources'].append(ref)
for plant in plants:
    plant['stemDiameterCm']={'rose':.3,'peony':.4,'tulip':.45,'ranunculus':.22,'anemone':.24,'lisianthus':.24,'lily':.4,'dahlia':.38}.get(plant['id'],.18 if plant['role'] in ['focal','secondary','line','mass'] else .1)
next(p for p in jewelryComponents if p['id']=='band-wide')['thicknessMm']=1.8
next(c for c in cuts if c['id']=='round')['supportedSettings'] += ['pave','shared-prong','channel']
for p in jewelPatterns:
    p['compatibleCuts']=[c['id'] for c in cuts if p['setting'] in c['supportedSettings']] if p['defaultCut'] else []
    if p['defaultCut'] and p['defaultCut'] not in p['compatibleCuts']:raise ValueError(p['id'])

for filename,data in [('sources',sources),('materials',materials),('baking',dict(components=baking,recipes=recipes)),('flowers',dict(plants=plants,forms=forms,bouquets=bouquets)),('jewelry',dict(components=jewelryComponents,cuts=cuts,patterns=jewelPatterns))]:
    (ROOT/(filename+'.json')).write_bytes((json.dumps(data,ensure_ascii=False,indent=2)+'\n').encode())
print(json.dumps(dict(sources=len(sources),materials=len(materials),bakingComponents=len(baking),recipes=len(recipes),plants=len(plants),bouquets=len(bouquets),jewelryComponents=len(jewelryComponents),jewelryPatterns=len(jewelPatterns))))
